/// English strings. This map is also the fallback for any key a translation
/// has not covered yet, so the UI can never render a raw key.
const Map<String, String> stringsEn = <String, String>{
  // ---------------------------------------------------------------- general --
  'appName': 'Saba',
  'ok': 'OK',
  'cancel': 'Cancel',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'remove': 'Remove',
  'retry': 'Retry',
  'close': 'Close',
  'next': 'Next',
  'back': 'Back',
  'done': 'Done',
  'confirm': 'Confirm',
  'search': 'Search',
  'apply': 'Apply',
  'clear': 'Clear',
  'clearAll': 'Clear all',
  'seeAll': 'See all',
  'loading': 'Loading',
  'refresh': 'Refresh',
  'share': 'Share',
  'optional': 'Optional',
  'required': 'Required',
  'yes': 'Yes',
  'no': 'No',
  'submit': 'Submit',
  'skip': 'Skip',
  'select': 'Select',
  'total': 'Total',
  'subtotal': 'Subtotal',
  'decrease': 'Decrease',
  'increase': 'Increase',
  'quantity': 'Quantity',
  'price': 'Price',
  'status': 'Status',
  'from': 'From',
  'to': 'To',

  // ----------------------------------------------------------------- errors --
  'errorGeneric': 'Something went wrong. Please try again.',
  'errorNetwork': 'No internet connection. Check your network and try again.',
  'errorTimeout': 'The request took too long. Please try again.',
  'errorServer': 'The server is temporarily unavailable. Please try again.',
  'errorNotFound': 'We could not find what you were looking for.',
  'errorUnauthorized': 'Your session has expired. Please sign in again.',
  'errorForbidden': 'You do not have permission to do that.',
  'errorValidation': 'Please check the highlighted fields.',
  'errorConflict': 'That action conflicts with the current state.',
  'errorPayment': 'The payment could not be completed.',
  'errorInventory': 'There is not enough stock available.',
  'errorParsing': 'We received an unexpected response from the server.',
  'errorCancelled': 'The request was cancelled.',
  'errorExternalService': 'An external service is unavailable right now.',

  // ------------------------------------------------------------ empty states --
  'emptyTitle': 'Nothing here yet',
  'emptyCart': 'Your cart is empty',
  'emptyCartMessage': 'Browse the marketplace and add items to get started.',
  'emptyWishlist': 'Your wishlist is empty',
  'emptyWishlistMessage': 'Tap the heart on any product to save it here.',
  'emptyOrders': 'No orders yet',
  'emptyOrdersMessage': 'Your orders will appear here once you buy something.',
  'emptySearch': 'No results found',
  'emptySearchMessage': 'Try a different keyword or adjust your filters.',
  'emptyNotifications': 'No notifications',
  'emptyAddresses': 'No saved addresses',
  'emptyProducts': 'No products found',
  'emptyConversations': 'No conversations yet',
  'emptyTickets': 'No support tickets',
  'startShopping': 'Start shopping',

  // ------------------------------------------------------------------- auth --
  'signIn': 'Sign in',
  'phoneTaken': 'This number already has an account.',
  'signInInstead': 'Sign in instead',
  'openStoreOnSaba': 'Open a store on Saba',
  'signOut': 'Sign out',
  'signUp': 'Create account',
  'welcomeToSaba': 'Welcome to Saba',
  'signInSubtitle': 'Sign in to continue shopping',
  'email': 'Email',
  'emailHint': 'you@example.com',
  'password': 'Password',
  'confirmPassword': 'Confirm password',
  'newPassword': 'New password',
  'fullName': 'Full name',
  'phone': 'Phone number',
  'country': 'Country',
  'city': 'City',
  'forgotPassword': 'Forgot password?',
  'forgotPasswordTitle': 'Reset your password',
  'forgotPasswordSubtitle':
      'Enter your email and we will send you a reset link.',
  'sendResetLink': 'Send reset link',
  'resetLinkSent': 'If that email is registered, a reset link is on its way.',
  'resetPasswordTitle': 'Choose a new password',
  'changePassword': 'Change password',
  'passwordChanged': 'Your password has been changed.',
  'noAccount': 'Do not have an account?',
  'createAnAccount': 'Create an account',
  'staffUseWebPanel': "Saba's staff sign in on the web panel, not in the app.",
  'exampleTemplate': 'e.g. {example}',
  'exPersonName': 'Ahmed Kareem',
  'exStreet': 'St. 14, alley 7, house 22',
  'exInstructions': 'Call when you reach the mosque',
  'exTicketSubject': 'My order has not arrived',
  'exTicketDescription': 'Order SB-100003 says delivered, but nothing came.',
  'exReport': 'The photos show a different model',
  'exReview': 'Fast delivery, well packed',
  'exCancel': 'I ordered the wrong size',
  'exReturn': 'The screen arrived cracked',
  'exProductNameAr': 'سماعة لاسلكية',
  'exProductNameEn': 'Wireless earbuds',
  'exProductDescription':
      'Bluetooth earbuds, 30-hour battery, charging case included.',
  'exWarranty': '1 year store warranty',
  'exStoreName': 'Karrada Phones',
  'exStoreDescription': 'Phones and accessories in Karrada since 2015.',
  'exBusinessAddress': 'Karrada Inner St., near Babel Hotel',
  'exDriverName': 'Ali Hassan',
  'exCouponCode': 'SAVE10',
  'exRepeatPassword': 'The same password again',
  'haveAccount': 'Already have an account?',
  'createCustomerAccount': 'Create a customer account',
  'registerAsMerchant': 'Sell on Saba',
  'accountType': 'Account type',
  'customer': 'Customer',
  'merchant': 'Merchant',
  'customerAccountDescription': 'Buy from thousands of sellers',
  'merchantAccountDescription': 'Open a store and start selling',
  'signOutConfirmTitle': 'Sign out?',
  'signOutConfirmMessage': 'You will need to sign in again to continue.',
  'merchantPendingApproval':
      'Your store is awaiting approval. You can sign in, but selling is disabled until Saba approves it.',
  'storeReviewAfterSignUp':
      'Once you sign up, Saba checks your store. You can sell as soon as it is approved.',

  // ------------------------------------------------------------- validation --
  'validationRequired': 'This field is required',
  'validationEmail': 'Enter a valid email address',
  'validationPasswordLength': 'Password must be at least 8 characters',
  'passwordHelper': 'At least 8 characters.',
  'validationPasswordMatch': 'Passwords do not match',
  'validationPhone': 'Enter a valid phone number',
  'validationMinLengthTemplate': 'Too short. Use at least {count}.',
  'validationNumber': 'Enter a valid number',
  'validationPositive': 'Enter a value greater than zero',

  // --------------------------------------------------------------- navigation --
  'navHome': 'Home',
  'navCategories': 'Browse',
  'navCart': 'Cart',
  'navOrders': 'Orders',
  'navAccount': 'Account',
  'navDashboard': 'Dashboard',
  'navProducts': 'Products',
  'navInventory': 'Inventory',
  'navAnalytics': 'Analytics',

  // --------------------------------------------------------------------- home --
  'homeGreeting': 'Discover great deals',
  'hello': 'Hello',
  'introducing': 'Introducing',
  'shopNow': 'Shop Now',
  'recentSearches': 'Recent searches',
  'popularSearches': 'People are looking for',
  'searchPlaceholder': 'Search products, brands and stores',
  'flashSales': 'Flash sales',
  'dealsOfTheDay': 'Deals of the day',
  'featuredProducts': 'Featured',
  'trendingProducts': 'Trending now',
  'bestSellers': 'Best sellers',
  'newArrivals': 'New arrivals',
  'recommendedForYou': 'Recommended for you',
  'allProducts': 'All products',
  'featuredMerchants': 'Featured stores',
  'popularBrands': 'Popular brands',
  'endsIn': 'Ends in',

  // ------------------------------------------------------------------ catalog --
  'categories': 'Categories',
  'browse': 'Browse',
  'searchProductsAndStores': 'Search products and stores',
  'allCategories': 'All categories',
  'brands': 'Brands',
  'products': 'Products',
  'filters': 'Filters',
  'sortBy': 'Sort by',
  'sortRelevance': 'Relevance',
  'sortNewest': 'Newest',
  'sortPriceLowHigh': 'Price: low to high',
  'sortPriceHighLow': 'Price: high to low',
  'sortBestSelling': 'Best selling',
  'upTo': 'Up to',
  'noResultsFiltered': 'Nothing matches all of those',
  'noResultsFilteredMessage':
      'Your filters are what emptied this list, not the shop. '
      'Remove them to see what is here.',
  'priceRange': 'Price range',
  'rating': 'Rating',
  'availability': 'Availability',
  'inStockOnly': 'In stock only',
  'onSale': 'On sale',
  'gridView': 'Grid view',
  'listView': 'List view',
  // ------------------------------------------------------------------ product --
  'addToCart': 'Add to cart',
  'buyNow': 'Buy now',
  'addToWishlist': 'Add to wishlist',
  'removeFromWishlist': 'Remove from wishlist',
  'inStock': 'In stock',
  'outOfStock': 'Out of stock',
  'lowStock': 'Only a few left',
  'soldBy': 'Sold by',
  'visitStore': 'Visit store',
  'visitStoreHint': 'See your store as buyers see it',
  'sizeGuide': 'Size guide',
  'readMore': 'Read more',
  'readLess': 'Read less',
  'description': 'Description',
  'warranty': 'Warranty',
  'returnPolicy': 'Return policy',
  'shippingInfo': 'Shipping',
  'estimatedDelivery': 'Estimated delivery',
  'relatedProducts': 'Related products',
  'selectVariant': 'Select an option',
  'selectVariantFirst': 'Please choose the product options first.',
  'addedToCart': 'Added to your cart',
  'addedToWishlist': 'Saved to your wishlist',
  'off': 'off',

  // --------------------------------------------------------------------- cart --
  'cart': 'Cart',
  'myCart': 'My cart',
  'saveForLater': 'Save for later',
  'savedForLater': 'Saved for later',
  'moveToCart': 'Move to cart',
  'removeItemTitle': 'Remove item?',
  'removeItemMessage': 'This item will be removed from your cart.',
  'couponCode': 'Coupon code',
  'applyCoupon': 'Apply',
  'couponApplied': 'Coupon applied',
  'couponsForYou': 'Coupons for you',
  'amountOffTemplate': '{amount} off',
  'firstOrderOnly': 'Your first order only',
  'onAnyOrder': 'On any order',
  'onOrdersOver': 'On orders over',
  'couponCopied': 'Code copied. It is also waiting in your cart.',
  'tapCouponToUse': 'Your coupons - tap one to use it',
  'removeCoupon': 'Remove coupon',
  'shipping': 'Shipping',
  'tax': 'Tax',
  'discount': 'Discount',
  'storeSubtotal': 'Store subtotal',
  'freeShipping': 'Free',
  'totalNote': 'One total for everything in your cart',
  'fromWord': 'from',
  'eachStoreShips': 'Each store ships on its own.',
  'deliveryFee': 'Delivery fee',
  'grandTotal': 'Total',
  'proceedToCheckout': 'Proceed to checkout',
  'itemsFromStore': 'Items from this store',
  'maxQuantityReached': 'You have reached the maximum quantity for this item.',

  // ----------------------------------------------------------------- checkout --
  'checkout': 'Checkout',
  'deliverTo': 'Deliver to',
  'change': 'Change',
  'changeAddress': 'Change address',
  'noDelivery': 'No delivery here',
  'delivery': 'Delivery',
  'deliveryWord': 'Delivery',
  'twoDeliveriesNote':
      'Each store sends its own parcel, so they may arrive on different days.',
  'codNote': 'Pay in cash when your order arrives. Nothing is charged now.',
  'deliveryAddress': 'Delivery address',
  'selectAddress': 'Select an address',
  'addAddress': 'Add address',
  'editAddress': 'Edit address',
  'defaultAddress': 'Default address',
  'setAsDefault': 'Set as default',
  'shippingMethod': 'Shipping method',
  'paymentMethod': 'Payment method',
  'orderReview': 'Review your order',
  'placeOrder': 'Place order',
  'orderPlaced': 'Order placed',
  'orderPlacedMessage': 'Thank you. Your order has been received.',
  'viewOrder': 'View order',
  'continueShopping': 'Continue shopping',
  'deliveryInstructions': 'Delivery instructions',
  'cashOnDelivery': 'Cash on delivery',
  'card': 'Credit or debit card',
  'wallet': 'Digital wallet',
  'bankTransfer': 'Bank transfer',
  'totalsRecalculated':
      'Totals are calculated by the server and may differ from the estimate.',

  // ------------------------------------------------------------------ address --
  'addresses': 'Addresses',
  'state': 'Governorate',
  'district': 'District',
  'street': 'Street',
  'building': 'Building',
  'apartment': 'Apartment',
  'postalCode': 'Postal code',
  'deleteAddressTitle': 'Delete address?',
  'deleteAddressMessage': 'This address will be permanently removed.',

  // ------------------------------------------------------------------- orders --
  'orders': 'Orders',
  'myOrders': 'My orders',
  'orderNumber': 'Order number',
  'orderDate': 'Order date',
  'orderTimeline': 'Timeline',
  'orderItems': 'Items',
  'orderDetails': 'Order details',
  'notAvailable': 'Not available',
  'invoice': 'Invoice',
  'cancelOrder': 'Cancel order',
  'cancelOrderTitle': 'Cancel this order?',
  'cancelOrderMessage': 'This cannot be undone.',
  'requestReturn': 'Request a return',
  'returnReason': 'Reason',
  'orderStatusAll': 'All',
  'orderStatusPending': 'Pending',
  'orderStatusConfirmed': 'Confirmed',
  'orderStatusProcessing': 'Processing',
  'stepPreparing': 'Preparing',
  'expectedArrivalTemplate': 'Expected: {time}',
  'orderFollowsSlowestTemplate':
      'The order shows the step of the store furthest behind: {status}.',
  'orderStatusShipped': 'Shipped',
  'orderStatusDelivered': 'Delivered',
  'orderStatusCancelled': 'Cancelled',
  'orderStatusReturned': 'Returned',
  'orderStatusRefunded': 'Refunded',
  'paymentStatus': 'Payment',
  'deliveryStatus': 'Delivery',

  // ------------------------------------------------------------------ account --
  'account': 'Account',
  'myProfile': 'My profile',
  'editProfile': 'Edit profile',
  'wishlist': 'Wishlist',
  'notifications': 'Notifications',
  'messages': 'Messages',
  'support': 'Support',
  'settings': 'Settings',
  'language': 'Language',
  'theme': 'Appearance',
  'themeSystem': 'System default',
  'themeLight': 'Light',
  'themeDark': 'Dark',
  'deleteAccount': 'Delete account',
  'deleteAccountTitle': 'Delete your account?',
  'deleteAccountMessage':
      'This permanently removes your account and cannot be undone.',
  'profileUpdated': 'Profile updated',
  'guestTitle': 'You are not signed in',
  'guestMessage': 'Sign in to see your orders, wishlist and account.',

  // ----------------------------------------------------------------- merchant --
  'merchantDashboard': 'Dashboard',
  'myStore': 'My store',
  'todaySales': 'Today',
  'totalSales': 'Total sales',
  'revenue': 'Revenue',
  'pendingOrders': 'Pending orders',
  'lowStockItems': 'Low stock',
  'outOfStockItems': 'Out of stock',
  'totalProducts': 'Products',
  'totalOrders': 'Orders',
  'topProducts': 'Top products',
  'myProducts': 'My products',
  'addProduct': 'Add product',
  'editProduct': 'Edit product',
  'productName': 'Product name',
  'sku': 'SKU',
  'barcode': 'Barcode',
  'stock': 'Stock',
  'originalPrice': 'Original price',
  'saveDraft': 'Save draft',
  'submitForApproval': 'Submit for approval',
  'productDraft': 'Draft',
  'productPendingApproval': 'Pending approval',
  'productApproved': 'Approved',
  'productRejected': 'Rejected',
  'inventory': 'Inventory',
  'adjustStock': 'Adjust stock',
  'availableStock': 'Available',
  'reservedStock': 'Reserved',
  'soldStock': 'Sold',
  'lowStockThreshold': 'Low stock threshold',
  'merchantOrders': 'Store orders',
  'updateOrderStatus': 'Update status',
  'analytics': 'Analytics',
  'payouts': 'Payouts',
  'grossSales': 'Gross sales',
  'commission': 'Platform commission',
  'netEarnings': 'Net earnings',
  'pendingPayout': 'Pending payout',
  'availablePayout': 'Available',
  'averageOrderValue': 'Average order value',
  'storeSettings': 'Store settings',
  'storeName': 'Store name',
  'storeDescription': 'Store description',
  'businessType': 'Business type',
  'businessAddress': 'Business address',

  // ------------------------------------------------------------------ support --
  'supportTickets': 'Support tickets',
  'newTicket': 'New ticket',
  'ticketSubject': 'Subject',
  'ticketCategory': 'Category',
  'ticketDescription': 'Describe the issue',
  'ticketStatusOpen': 'Open',
  'ticketStatusInProgress': 'In progress',
  'ticketStatusWaiting': 'Waiting for you',
  'ticketStatusResolved': 'Resolved',
  'ticketStatusClosed': 'Closed',
  'typeMessage': 'Type a message',
  'send': 'Send',
  'photo': 'Photo',
  'sendPhoto': 'Send a photo',
  'photoDeleted': 'Photo deleted',
  'photoRemovedBySaba': 'Photo removed by Saba',

  // ------------------------------------------------------------ notifications --
  'markAllRead': 'Mark all as read',

  // ----------------------------------------------------------------- misc --
  'or': 'or',
  'all': 'All',
  'update': 'Update',
  'create': 'Create',
  'reset': 'Reset',
  'viewDetails': 'View details',
  'saveChanges': 'Save changes',
  'stores': 'Stores',
  'store': 'Store',
  'signInRequired': 'Sign in required',
  'signInToContinue': 'Sign in to continue',
  'orderSummary': 'Order summary',
  'shippingAddress': 'Shipping address',
  'trackOrder': 'Track order',
  'selectCountry': 'Select a country',
  'selectCity': 'Select a city',
  'statusApproved': 'Approved',
  'statusRejected': 'Rejected',
  'statusSuspended': 'Suspended',
  'statusActive': 'Active',
  'statusInactive': 'Inactive',
  'attachments': 'Attachments',
  'sortAndFilter': 'Sort and filter',
  'noImage': 'No image',
  'salesChart': 'Sales',
  'thisWeek': 'This week',
  'thisMonth': 'This month',
  'thisYear': 'This year',
  'today': 'Today',
  // -------------------------------------------------------- merchant extra --
  'refunds': 'Refunds',
  'returns': 'Returns',
  'cancellations': 'Cancellations',
  'productsSold': 'Products sold',
  'customers': 'Customers',
  'orderStatusNew': 'New',
  'requestPayout': 'Request payout',
  'payoutHistory': 'Payout history',
  'noPayouts': 'No payouts yet',
  'stockAdjustment': 'Stock adjustment',
  'newQuantity': 'New quantity',
  'reason': 'Reason',
  'searchProducts': 'Search your products',
  'period': 'Period',
  'noProductsYet': 'You have no products yet',
  'addFirstProduct': 'Add your first product',
  'deleteProductTitle': 'Delete product?',
  'deleteProductMessage': 'This product will be removed from your store.',
  'category': 'Category',
  'selectCategory': 'Select a category',
  'brand': 'Brand',
  'brandHint': 'Type a brand, or pick one',
  'brandHelp': 'A brand not on the list is checked by Saba with the product.',
  'markAsShipped': 'Mark as shipped',
  'nextStatus': 'Advance status',
  'customerName': 'Customer',
  'noStoreYet': 'No store found',
  // ------------------------------------------------------------------ media --
  'addPhotos': 'Add photos',
  'addPhoto': 'Add photo',
  'takePhoto': 'Take a photo',
  'chooseFromGallery': 'Choose from gallery',
  'attachFile': 'Attach a file',
  'uploading': 'Uploading',
  'uploadFailed': 'Upload failed',
  'retryUpload': 'Retry upload',
  'cancelUpload': 'Cancel upload',
  'removeFile': 'Remove file',
  'setAsPrimary': 'Set as main image',
  'primaryImage': 'Main image',
  'noFilesSelected': 'No files selected',
  'maxFilesReached': "That's as many as you can add here.",
  'mediaTooLarge': 'This file is too large',
  'mediaUnsupportedType': 'This file type is not supported',
  'mediaUnsupportedExtension': 'This file extension is not supported',
  'mediaImageTooSmall': 'This image is too small',
  'mediaImageTooLarge': 'This image is too large',
  'mediaUnreadable': 'This file could not be read',
  'someFilesRejected': 'Some files were not added',
  'paymentPending': 'Payment pending',
  'paymentPendingMessage':
      'We have not received confirmation from the payment provider yet.',
  'paymentConfirmed': 'Payment confirmed',
  'paymentFailedTitle': 'Payment not completed',
  'paymentFailedMessage':
      'The payment did not go through and nothing was charged. Place the order again, or ask Support for help.',
  'checkPaymentStatus': 'Check payment status',
  'awaitingPayment': 'Awaiting payment',

  // ------------------------------------------- merchant product media --
  'productImages': 'Product images',
  'productImagesHint':
      'The first photo is the main one. Tap another photo to make it the main one.',
  'productBasics': 'The basics',
  'priceAndStock': 'Price and stock',
  'productCodes': 'SKU and barcode',
  'productPolicies': 'Warranty and returns',
  'variants': 'Variants',
  'variantsHint':
      'Add options such as Color or Storage. Every combination becomes a variant with its own price and stock.',
  'addOption': 'Add option',
  'editOption': 'Edit option',
  'optionName': 'Option name',
  'optionNameHint': 'Color, Size, Storage…',
  'optionValues': 'Values',
  'optionValuesHint': 'Red, Blue, Green (separate with commas)',
  'inheritPrice': 'Same as product',

  // ------------------------------------------- returns, refunds, invoice --
  'myReturns': 'My returns',
  'noReturns': 'No returns yet',
  'noReturnsMessage':
      'Returns you request will appear here with their refund progress.',
  'returnStatusRequested': 'Requested',
  'returnStatusApproved': 'Approved',
  'returnStatusRejected': 'Rejected',
  'returnStatusPickup': 'Pickup scheduled',
  'returnStatusReceived': 'Received',
  'returnStatusRefundPending': 'Refund pending',
  'returnStatusRefunded': 'Refunded',
  'returnStatusClosed': 'Closed',
  'returnDetails': 'Return details',
  'returnedItems': 'Returned items',
  'returnRequestedOn': 'Requested on',
  'returnPhotos': 'Photos',
  'rejectionReason': 'Reason for rejection',
  'returnProgress': 'Progress',
  'refund': 'Refund',
  'refundStatus': 'Refund status',
  'refundAmount': 'Refund amount',
  'refundMethod': 'Refunded to',
  'refundReference': 'Reference',
  'refundProcessedOn': 'Processed on',
  'refundExpectedBy': 'Expected by',
  'refundStatusPending': 'Pending',
  'refundStatusProcessing': 'Processing',
  'refundStatusCompleted': 'Completed',
  'refundStatusFailed': 'Failed',
  'noRefundYet': 'No refund has been raised for this return yet.',
  'viewInvoice': 'View invoice',
  'invoiceNumber': 'Invoice number',
  'issuedOn': 'Issued on',
  'billedTo': 'Billed to',
  'unitPrice': 'Unit price',
  'amount': 'Amount',
  'downloadInvoice': 'Download PDF',
  'invoiceTotals': 'Totals',
  'amountPaid': 'Amount paid',
  'cancelReason': 'Reason for cancelling',
  'selectCancelReason': 'Why are you cancelling?',
  'cancelReasonChangedMind': 'I changed my mind',
  'cancelReasonFoundCheaper': 'I found it cheaper elsewhere',
  'cancelReasonDeliveryTooSlow': 'Delivery is taking too long',
  'cancelReasonOrderedByMistake': 'I ordered it by mistake',
  'cancelReasonOther': 'Another reason',
  'cancelReasonNote': 'Tell us more',
  'cancelReasonRequired': 'Please choose a reason',

  // ------------------------------------------------- after the sale --
  'returnReasonDamaged': 'It arrived damaged',
  'returnReasonWrongItem': 'The wrong item arrived',
  'returnReasonNotAsDescribed': 'It is not as described',
  'returnReasonMissingParts': 'Parts are missing',
  'returnReasonChangedMind': 'I changed my mind',
  'returnReasonOther': 'Another reason',
  'emptyFilteredList': 'Nothing under this filter',
  'emptyFilteredListMessage':
      'Nothing you have is in this state right now. Everything else is still under All.',
  'showAll': 'Show all',
  'ticketCategoryOrder': 'A problem with an order',
  'ticketCategoryPayment': 'Payment or billing',
  'ticketCategoryDelivery': 'Delivery or shipping',
  'ticketCategoryReturn': 'A return or refund',
  'ticketCategoryProduct': 'A question about a product',
  'ticketCategoryAccount': 'My account',
  'ticketCategoryOther': 'Something else',
  'emptyTicketsMessage': 'Open one and support will reply here.',
  'emptyProductsMessage': 'This store has nothing listed right now.',
  'emptyNotificationsMessage':
      'Order updates, replies and price drops land here.',
  'addressNickname': 'Name this address',
  'addressNicknameHint': 'Home, Work, Office',
  'addressWho': 'Who is it for',
  'addressWhere': 'Where to deliver',
  'addressExtras': 'Anything else',
  'emptyAddressesMessage':
      'Add one and it will be offered at checkout, so you only type it once.',
  'languageSystem': 'Follow the device',
  'languageSystemHint': 'Saba uses whatever language your phone is set to.',
  'noReviewsMessage': 'Be the first to review this product.',
  'merchantReplied': 'Response from the seller',
  'reportReview': 'Report review',
  'report': 'Report',
  'reportProduct': 'Report product',
  'reportStore': 'Report store',
  'reportChat': 'Report chat',
  'reportThanks': 'Thanks. Saba will look at it.',
  'block': 'Block',
  'unblock': 'Unblock',
  'blockTitle': 'Block this chat?',
  'blockMessage':
      'Nobody can write here until you unblock it. You can still read it, '
      'and orders carry on.',
  'chatBlockedByMe': 'You blocked this chat, so nobody can write here.',
  'chatBlocked': 'Messages are off in this chat.',
  'storeReviews': 'Store reviews',
  'reportReasonLabel': 'Why are you reporting this?',
  'reportCounterfeit': 'Counterfeit or fake',
  'reportProhibited': 'Prohibited item',
  'reportMisleading': 'Misleading description or images',
  'reportOffensive': 'Offensive content',
  'reportSpam': 'Spam',
  'reportOther': 'Another reason',
  'reportDetails': 'Tell us more',
  'reportSubmitted': 'Thank you. Our team will review this.',
  'reportReasonRequired': 'Please choose a reason',
  'noReviews': 'No reviews yet',
  'clearHistoryTitle': 'Clear search history?',
  'clearHistoryMessage':
      'Your recent searches will be removed from this device and your account.',
  'noMessagesYet': 'No messages yet',
  'noMessagesYetMessage':
      'Ask about a product, an order or delivery. The reply will appear here.',
  'selectItemsToReturn': 'Choose at least one item to return.',
  'removeOptionTitle': 'Remove this option?',
  'removeOptionMessage':
      'The variant rows it created will go, along with the SKU, price and stock typed into them.',
  'variantsKeptIfEmpty':
      'Existing variants are kept while this is empty. Add an option to replace them.',
  'waitForUploads': 'Wait for the images to finish uploading.',
  'keepOrder': 'Keep order',
  'storeUpdated': 'Store updated',
  'moreOptions': 'More options',
  'verified': 'Verified',

  // ---------------------------------------------- merchant dashboard --
  'revenueThisMonth': 'Revenue this month',
  'needsYouToday': 'Needs you today',
  'oldestWaiting': 'Oldest has been waiting',
  'stillListedNotBuyable': 'They stay listed but cannot be bought',
  'replyWithin': 'Reply within',
  'ordersThisMonth': 'Orders this month',
  'storeRating': 'Store rating',
  'vsLastMonth': 'vs last month',
  'previousPeriod': 'Previous period',
  'lastMonthSame': 'Last month, same',
  'noSalesYet': 'No sales in this period',
  'storeOpen': 'Store open',
  'storeClosed': 'Store closed',
  'allCaughtUp': 'Nothing needs you right now',
  'viewAll': 'View all',

  // ------------------------------------------------- merchant orders --
  'toConfirm': 'To confirm',
  'preparing': 'Preparing',
  'decline': 'Decline',
  'whyDeclining': 'Why are you declining?',
  'declineNote':
      'Declining asks you for a reason and cancels the order. Nothing was paid, so nothing is handed back. Every decline counts against your store rating.',
  'reasonOutOfStock': 'Out of stock',
  'reasonCannotFulfil': 'Cannot fulfil in time',
  'reasonAddressProblem': 'Problem with the address',
  'reasonCustomerAsked': 'Customer asked to cancel',
  'orderDeclined': 'Order declined. The customer has been told.',

  // ----------------------------------------------- merchant products --
  'searchYourProducts': 'Search your products',
  'lowStockFilter': 'Low stock',
  'outFilter': 'Out',
  'hiddenFilter': 'Hidden',
  'hidden': 'Hidden',
  'hideFromShoppers': 'Hide from shoppers',
  'showToShoppers': 'Show to shoppers',
  'productHidden': 'Hidden. Shoppers no longer see it.',
  'productShown': 'Shown. Shoppers can buy it again.',
  'inStockCount': 'in stock',
  'leftCount': 'left',
  'restock': 'Restock',
  'setStock': 'Set stock',
  'flashSale': 'Flash sale',
  'flashSaleUntilTemplate': 'Flash sale until {time}',
  'salePrice': 'Sale price',
  'normalPriceTemplate': 'The normal price is {price}.',
  'salePriceInvalid': 'Enter the sale price.',
  'salePriceNotLower': 'The sale price must be lower than the normal price.',
  'endSaleQuestion': 'End this flash sale now?',
  'endSaleWarning': 'Shoppers pay the normal price again straight away.',
  'saleEndPassed': 'Pick an end time that has not passed.',
  'startSale': 'Start sale',
  'endSaleNow': 'End sale now',
  'flashSaleSaved': 'Flash sale saved.',
  'flashSaleEnded': 'Flash sale ended.',
  'noProductsMatch': 'No products match',
  'productsRejected': 'products need changes',
  'rejectedNeedsEdit': 'They were not approved and are not on sale',

  // ------------------------------------------- entry and onboarding --
  'sabaTagline': "Iraq's marketplace. Many stores, one cart.",
  'chooseYourLanguage': 'Choose your language',
  'changeLanguageLater': 'You can change this later in Account.',
  'englishName': 'English',
  'englishOther': 'الإنجليزية',
  'arabicName': 'العربية',
  'arabicOther': 'Arabic',
  'alreadyHaveAccount': 'Already have an account?',
  'whatsYourNumber': "What's your number?",
  'phoneStepCustomerMessage':
      "We'll text you a 6-digit code. Stores call this number about your orders.",
  'phoneStepMerchantMessage':
      "We'll text you a 6-digit code. Shoppers and Saba call this number about your store.",
  'sendCode': "Send code",
  'enterTheCode': "Enter the code",
  'codeSentTo': "Code sent to",
  'verificationCode': "Verification code",
  'changeNumber': "Change number",
  'didNotGetCode': "Didn't get it?",
  'resendCode': "Resend code",
  'codeSentAgain': "A new code is on its way.",
  'demoCodeNote': "Demo build, no SMS is sent. Your code is",
  'validationOtpLength': "Enter all 6 digits.",
  'verify': "Verify",
  'verifyNumberTitle': "Check your number",
  'verifyNumberWhy':
      "Saba needs to check your number once. Enter the code we just sent.",
  'verifyNumberToSignIn':
      "Saba needs to check your number once. Ask for a code, then sign in with it.",
  'numberVerified': "Number verified",
  'businessTypeIndividual': "Individual",
  'businessTypeSoleProprietorship': "Sole proprietorship",
  'businessTypeCompany': "Company",
  'businessTypeDistributor': "Distributor",
  'demoAccountsTitle': "Demo accounts",
  'demoAccountsNote': "Tap one to fill the form. Any password works.",
  'demoShopper': "Shopper",
  'demoMerchant': "Merchant",
  'yourProfile': "Your profile",
  'yourProfileSubtitle': "Tell us a little about yourself.",
  'yourStore': "Your store",
  'yourStoreSubtitle': "This is what buyers will see.",
  'storeSignUpSubtitle':
      "You, your store and its city. The rest can wait for store settings.",
  'stepWord': "Step",
  'ofWord': "of",
  'chooseBusinessType': "Choose a business type",
  'changeLanguage': "Change language",
  'accountYou': "You",
  'accountGetHelp': "Get help",
  'accountSecurity': "Security and settings",
  'itemRemoved': 'Removed from cart',
  'undo': 'Undo',
  'removeUnavailable': 'Remove unavailable items',
  'searchInStore': 'Search in this store',
  'noResultsInStore': 'Nothing in this store matches',
  'noResultsInStoreMessage':
      'Your search is what emptied this list, not the shop. Clear it to see everything here.',
  'copiedToClipboard': 'Copied',
  'copy': 'Copy',
  'makeMainImage': 'Use as main image',
  'message': 'Message',
  'emptyConversationsHint':
      'To ask a store something, tap Message on a product, a store page or an order.',
  'emptyConversationsStoreHint':
      'When a customer writes to your store, it shows here.',
  'aboutTopicTemplate': 'About {topic}: ',
  'aboutOrderTemplate': 'About order {number}: ',
  'codPlacedMessage': 'Have the cash ready: you pay when it arrives.',
  'payOnDelivery': 'Pay on delivery',
  'paymentPaid': 'Paid',
  'paymentFailedShort': 'Payment failed',
  'coupons': 'Coupons',
  'couponsTileHint': 'Discount codes for your customers',
  'newCoupon': 'New coupon',
  'editCoupon': 'Edit coupon',
  'couponCodeHelper':
      '3 to 15 letters or numbers. Customers type it, or tap it.',
  'suggestCode': 'Suggest',
  'discountPercent': 'Percent',
  'discountAmountIqd': 'Amount (IQD)',
  'discountLabel': 'Discount',
  'minimumOrderOptional': 'Minimum order',
  'minimumOrderHelper': 'Counted on what is bought from your store.',
  'startsOn': 'Starts',
  'endsOn': 'Ends',
  'noEndDate': 'No end date',
  'usageLimitOptional': 'Times it can be used',
  'usageLimitHelper': 'Leave empty for no limit.',
  'couponUsedTemplate': 'Used {times}',
  'couponUsedOfTemplate': '{used} of {limit} used',
  'couponScheduled': 'Scheduled',
  'couponPaused': 'Paused',
  'couponEnded': 'Ended',
  'couponUsedUp': 'Used up',
  'untilDateTemplate': 'Until {date}',
  'startsDateTemplate': 'Starts {date}',
  'pauseCoupon': 'Pause',
  'resumeCoupon': 'Resume',
  'deleteCouponQuestion': 'Delete this coupon?',
  'deleteCouponMessage': 'Customers will not be able to use it any more.',
  'couponSaved': 'Coupon saved',
  'couponDeleted': 'Coupon deleted',
  'noCouponsYet': 'No coupons yet',
  'noCouponsYetMessage':
      'Make a discount code for your store. Customers see it on your store page, on Home and in their cart.',
  'couponPreview': 'How customers see it',
  'couponsFromTemplate': 'Coupons from {store}',
  'atStoreTemplate': 'At {store}',
  'couponCodeInvalid': 'Use 3 to 15 letters or numbers.',
  'discountInvalid': 'Enter a discount above 0.',
  'percentTooHigh': 'A percentage can be at most 90.',
  'endBeforeStart': 'The end date must be after the start.',
  'wholeNumber': 'Enter a whole number.',
  'yesterday': 'Yesterday',
  'deleteStoreAccountHint':
      'Closes your store now. Deleted once your orders, returns and last '
      'bill are done.',
  'deleteStoreAccountTitle': "Delete your store's account?",
  'deleteStoreAccountMessage':
      'Your store closes now and takes no new orders.\n\n'
      'Your account and personal details are deleted once your open orders '
      'are finished, the 7-day return window after your last delivery has '
      'passed, and your last bill is paid. That bill is for the month of '
      'your last delivery and is due when the month ends, so this takes at '
      "least until then. We'll send an SMS to your number when it's done. "
      'If a bill stays unpaid, your account is not deleted.\n\n'
      'Orders, invoices, returns and bills are kept as records, as the law '
      'requires.',
  'storeDeletionTitle': 'Your account is being deleted',
  'storeDeletionAskedTemplate': 'Asked on {date}. Your store is closed.',
  'storeDeletionWaitsFor': 'It is deleted once none of these is left:',
  'stillOpenOrdersTemplate': 'Orders still open: {count}',
  'openReturnsTemplate': 'Returns to settle: {count}',
  'stillOwedTemplate': 'Owed to Saba: {amount}',
  'returnsOpenUntilTemplate': 'Returns open until {date}',
  'storeDeletionSoon':
      'Nothing is left open: it will be deleted within the hour.',
  'storeDeletionSms': "We'll send an SMS to your number when it's done.",
  'storeDeletionUnpaid': 'If a bill stays unpaid, your account is not deleted.',
  'keepMyAccount': 'Keep my account',
  'keepMyAccountTitle': 'Keep your account?',
  'keepMyAccountMessage':
      "Your account won't be deleted. Your store stays closed until you "
      'open it from your dashboard.',
  'accountKept': "Your account won't be deleted.",
  'storeBeingDeleted': 'Closed: account being deleted',
  'deleteAccountHint':
      'Removes your account and saved details. This cannot be undone.',
  'yourCity': 'Your city',
  'chooseYourCity': 'Choose your city',
  'deliverToTemplate': 'Deliver to {city}',
  'cityRequired': 'Choose the city.',
  'useEmailInstead': 'Use email instead',
  'usePhoneInstead': 'Use phone number instead',
  'emailOptional': 'Email',
  'forgotPasswordPhoneSubtitle':
      "Enter your phone number and we'll send you a code by SMS.",
  'saveNewPassword': 'Save new password',
  'phoneSignInHelper':
      'You sign in with this number. To change it, contact support.',
  'area': 'Area or neighbourhood',
  'areaHint': 'e.g. Al-Mansour',
  'nearestLandmark': 'Nearest landmark',
  'nearestLandmarkHint': 'e.g. next to Al-Rasheed Mosque',
  'streetAndHouse': 'Street, alley and house no.',
  'driverCallsThisNumber': 'The driver calls this number when on the way.',
  'cashToEachDriver': 'Cash to each driver',
  'cashToEachDriverNote':
      "Each store's driver collects only that store's part.",
  'cashToDriver': 'Cash to the driver',
  'paidToDriver': 'Paid to the driver',
  'collectInCash': 'Collect in cash',
  'iqdSteps': 'Use steps of 250 IQD, like 12,250 or 12,500.',
  'deliverySameDay': 'Same day',
  'delivery1to2Days': '1–2 days',
  'delivery2to3Days': '2–3 days',
  'delivery3to5Days': '3–5 days',
  'delivery5to7Days': '5–7 days',
  'noDeliveryToTemplate': "Doesn't deliver to {city}",
  'deliversToTemplate': 'Delivers to {city}',
  'addressCityNoteTemplate':
      'Your Home city is {home}. This order goes to {city}, where the address is.',
  'deliverySettings': 'Delivery',
  'whereYouDeliver': 'Where you deliver',
  'wholeIraq': 'All of Iraq',
  'onlyMyCity': 'Only my city',
  'feeInYourCity': 'Fee in your city',
  'feeOtherCities': 'Fee to other cities',
  'timeInYourCity': 'Time in your city',
  'timeOtherCities': 'Time to other cities',
  'zeroIsFree': 'Put 0 for free delivery.',
  'removeOrChangeAddress': 'Take its items out, or choose another address.',
  'chooseDeliveryTime': 'Choose a time',
  'call': 'Call',
  'orderStatusRefused': 'Refused',
  'callShopperFirst':
      'Call the shopper first to check the order and the address.',
  'iCalledConfirm': 'I called them: confirm',
  'whoDelivers': 'Who delivers it?',
  'driverName': "Driver's name",
  'courierPhone': 'Their phone',
  'refusedAtDoor': 'Refused at the door',
  'refusedConfirm':
      'The shopper refused the parcel? Its items go back on your shelf.',
  'driverLabel': 'Driver',
  'didYouReceive': 'Did you receive it?',
  'yesReceived': 'Yes, I got it',
  'noNotReceived': 'No',
  'receiptProblemNote': 'We told the store. They will call you.',
  'returnCashNote': 'The store picks the item up and hands your cash back.',
  'returnWindowNote': 'You can return it within 7 days of delivery.',
  'notOnThisReturn': 'Not on this return',
  'notDeliveredYetReturn':
      'Not delivered yet. It can be returned once it arrives.',
  'cancelledNothingToReturn': 'Cancelled, so there is nothing to return.',
  'returnedOrLate': 'Already returned, or its 7 days have passed.',
  'nothingToReturnNow': 'Nothing on this order can be returned now.',
  'returnRequests': 'Return requests',
  'approveReturn': 'Approve and pick up',
  'declineReturn': 'Decline',
  'cashHandedBack': 'Picked up, cash handed back',
  'oweSaba': 'What you owe Saba',
  'oweThisMonth': 'This month so far',
  'deliveredSales': 'Delivered sales',
  'returnedCash': 'Cash handed back on returns',
  'sabaShare': "Saba's share",
  'youOwe': 'You owe',
  'oweHowItWorks':
      'Only delivered orders count, and returns are taken off. The delivery fee is all yours. You pay Saba at the start of next month.',
  'pastMonths': 'Past months',
  'noPastMonths': 'No past months yet.',
  'billDue': 'Due',
  'billPaid': 'Paid',
  'billPaidOnTemplate': 'Paid {date}',
  'billNothingOwed': 'Nothing to pay',
  'storeClosedNow': 'Closed right now',
  'storeClosedBuyNote': 'This store is closed right now. Come back later.',
  'storeNowOpen': 'Your store is open. Shoppers can order.',
  'storeNowClosed':
      "Your store is closed. Shoppers can't order until you open it.",
  'nameInArabic': 'Name in Arabic',
  'nameInEnglish': 'Name in English',
  'validationArabicLetters': 'Write it in Arabic letters',
  'termsOfUse': 'Terms of use',
  'privacyPolicy': 'Privacy policy',
  'legalUpdated': 'Last updated 1 October 2026',
  'aboutSaba': 'About Saba',
  'agreeToTerms': "Creating an account means you agree to Saba's rules:",
  'returnRuleShort': '7 days to return, cash back',
  'returnRuleStore':
      'Returns: 7 days after delivery, cash back. The same rule at every store on Saba.',
  'allCities': 'All cities',
  'deliveryAvailable': 'Delivery available',

  // The demo admin: the one screen that answers what is waiting.

  // Rating the store that delivered, once an order has arrived (§20).
  'didYourOrderArrive': 'Did your order arrive?',
  'yesItArrived': 'Yes, it arrived',
  'returnDeclineUsed': 'It has been used',
  'returnDeclineIncomplete': 'Something is missing from the box',
  'returnDeclineNotAsSaid': "It isn't as the shopper said",
  'whyDecliningReturn': 'Why are you declining this return?',
  'confirmApproveReturn':
      'You collect the item and hand the cash back when you do.',
  'confirmCashBack': 'Did you hand the cash back? This finishes the return.',
  'howWasYourOrder': 'How was your order?',
  'notYet': 'Not yet',
  'notNow': 'Not now',
  'anythingToAdd': 'Anything to add?',
  'stockIsPerOption': 'Stock is set on each option below.',
  'merchantRejectedBanner':
      'Saba did not approve your store, so it cannot sell yet. Write to '
      'support to find out what to change and ask again.',
  'storePreview': 'This is how buyers see your store',
  'previewNotListed': "Only you can see this product. Buyers can't.",
  'backToDashboard': 'Dashboard',
  'setUpYourStore': 'Set up your store',
  'stepAddFirstProduct': 'Add your first product',
  'stepSetDelivery': 'Set your delivery fee and where you deliver',
  'stepWaitForApproval': "Wait for Saba's approval",
  'storeWaitingApproval': 'Waiting for approval',
  'storeApprovedOpen': 'Open for orders',
  'storeApprovedClosed': 'Closed by you',
  'storeNotApproved': 'Not approved',
  'sendForApproval': 'Send for approval',
  'sendForApprovalHint': 'Saba checks it, then it goes on sale.',
  'productSaved': 'Saved.',
  'priceStepHint': 'In steps of 250 IQD, like 12,250 or 12,500.',
  'waitingForApproval': 'Waiting for approval',
  'storeLogo': 'Store photo or logo',
  'previewWaitingMessage': 'Your products show here once Saba approves them.',
  'listSeparator': ', ',
  'nounItem': 'item|items',
  'nounCharacter': 'character|characters',
  'nounProduct': 'product|products',
  'nounStore': 'store|stores',
  'nounOrder': 'order|orders',
  'nounResult': 'result|results',
  'nounCustomer': 'customer|customers',
  'nounReturnRequest': 'return request|return requests',
  'nounDay': 'day|days',
  'nounHour': 'hour|hours',
  'nounMinute': 'minute|minutes',
  'nounSecond': 'second|seconds',
  'nounTime': 'time|times',
  'resendInTemplate': 'Resend in {time}',
  'waitingForTemplate': 'Waiting {time}',
  'toConfirmSuffix': 'to confirm',
  'waitingReplySuffix': 'waiting for your reply',
  'outOfStockSuffix': 'out of stock',
  'notApprovedSuffix': 'not approved',
  'freeDelivery': 'Free delivery',
  'takenDown': 'Taken down',
  'takenDownBySaba': 'Taken down by Saba',
  'sabaSaidNo': 'Saba did not approve this product',
  'fixAndResend': 'Change what the reason asks and send it again.',
  'editApprovedNote':
      'Changing the name, description, warranty, category, photos or '
      'options sends it back to Saba for review, and it leaves the shop '
      'until approved. Price and stock changes do not.',
  'noteOrderReceived': 'Order received',
  'reasonCustomerCancelled': 'Cancelled by the customer',
  'notInTotalTemplate': 'Not in your total: {reason}',
  'productNotFound': 'This product is not available',
  'productNotFoundMessage':
      'It may have been taken off sale, or the link is wrong.',
  'cancelledNothingCharged': 'Cancelled: none of this will be charged.',
  'refusedNothingPaid': 'Refused at the door: nothing was paid.',
  'storePhone': 'Store phone',
  'autoDeliverOnTemplate':
      'Not marked "Delivered" by {date}? Saba marks it delivered then, and the shopper is told.',
  'noteAutoDelivered':
      'Marked delivered automatically: it was on its way for 5 days.',
  'emptyStoreReturns': 'No returns yet',
  'emptyStoreReturnsMessage':
      'When a shopper asks to return something from your store, it shows here.',
  'returnNeedsAnswer': 'Open the order to approve or decline',
  'returnNeedsCash': 'Collect it, then mark the cash handed back',
};
