/// Arabic strings (right-to-left).
///
/// Any key missing here falls back to the English map, so a partial
/// translation degrades gracefully instead of showing a raw key.
const Map<String, String> stringsAr = <String, String>{
  // ---------------------------------------------------------------- general --
  'appName': 'سبأ',
  'ok': 'حسناً',
  'cancel': 'إلغاء',
  'save': 'حفظ',
  'delete': 'حذف',
  'edit': 'تعديل',
  'remove': 'إزالة',
  'retry': 'إعادة المحاولة',
  'close': 'إغلاق',
  'next': 'التالي',
  'back': 'رجوع',
  'done': 'تم',
  'confirm': 'تأكيد',
  'search': 'بحث',
  'apply': 'تطبيق',
  'clear': 'مسح',
  'clearAll': 'مسح الكل',
  'seeAll': 'عرض الكل',
  'loading': 'جارٍ التحميل',
  'refresh': 'تحديث',
  'share': 'مشاركة',
  'optional': 'اختياري',
  'required': 'مطلوب',
  'yes': 'نعم',
  'no': 'لا',
  'submit': 'إرسال',
  'skip': 'تخطي',
  'select': 'اختيار',
  'total': 'الإجمالي',
  'subtotal': 'المجموع الفرعي',
  'decrease': 'إنقاص',
  'increase': 'زيادة',
  'quantity': 'الكمية',
  'price': 'السعر',
  'status': 'الحالة',
  'from': 'من',
  'to': 'إلى',

  // ----------------------------------------------------------------- errors --
  'errorGeneric': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
  'errorNetwork': 'لا يوجد اتصال بالإنترنت. تحقق من الشبكة وحاول مجدداً.',
  'errorTimeout': 'استغرق الطلب وقتاً طويلاً. يرجى المحاولة مرة أخرى.',
  'errorServer': 'الخادم غير متاح مؤقتاً. يرجى المحاولة لاحقاً.',
  'errorNotFound': 'لم نتمكن من العثور على ما تبحث عنه.',
  'errorUnauthorized': 'انتهت جلستك. يرجى تسجيل الدخول مرة أخرى.',
  'errorForbidden': 'ليس لديك صلاحية للقيام بذلك.',
  'errorValidation': 'يرجى مراجعة الحقول المحددة.',
  'errorConflict': 'هذا الإجراء يتعارض مع الحالة الحالية.',
  'errorPayment': 'تعذّر إتمام عملية الدفع.',
  'errorInventory': 'لا تتوفر كمية كافية في المخزون.',
  'errorParsing': 'تلقّينا رداً غير متوقع من الخادم.',
  'errorCancelled': 'تم إلغاء الطلب.',
  'errorExternalService': 'إحدى الخدمات الخارجية غير متاحة حالياً.',

  // ------------------------------------------------------------ empty states --
  'emptyTitle': 'لا يوجد شيء هنا بعد',
  'emptyCart': 'سلتك فارغة',
  'emptyCartMessage': 'تصفّح المتجر وأضف المنتجات للبدء.',
  'emptyWishlist': 'المفضلة فارغة',
  'emptyWishlistMessage': 'اضغط على القلب في أي منتج لحفظه هنا.',
  'emptyOrders': 'لا توجد طلبات بعد',
  'emptyOrdersMessage': 'ستظهر طلباتك هنا بعد أول عملية شراء.',
  'emptySearch': 'لا توجد نتائج',
  'emptySearchMessage': 'جرّب كلمة أخرى أو عدّل عوامل التصفية.',
  'emptyNotifications': 'لا توجد إشعارات',
  'emptyAddresses': 'لا توجد عناوين محفوظة',
  'emptyProducts': 'لا توجد منتجات',
  'emptyConversations': 'لا توجد محادثات',
  'emptyTickets': 'لا توجد تذاكر دعم',
  'startShopping': 'ابدأ التسوق',

  // ------------------------------------------------------------------- auth --
  'signIn': 'تسجيل الدخول',
  'phoneTaken': 'هذا الرقم مسجّل بحساب.',
  'signInInstead': 'سجّل الدخول بدلاً من ذلك',
  'openStoreOnSaba': 'افتح متجرك على سبأ',
  'signOut': 'تسجيل الخروج',
  'signUp': 'إنشاء حساب',
  'welcomeToSaba': 'أهلاً بك في سبأ',
  'signInSubtitle': 'سجّل الدخول لمتابعة التسوق',
  'email': 'البريد الإلكتروني',
  'emailHint': 'you@example.com',
  'password': 'كلمة المرور',
  'confirmPassword': 'تأكيد كلمة المرور',
  'newPassword': 'كلمة المرور الجديدة',
  'fullName': 'الاسم الكامل',
  'phone': 'رقم الهاتف',
  'country': 'الدولة',
  'city': 'المدينة',
  'forgotPassword': 'نسيت كلمة المرور؟',
  'forgotPasswordTitle': 'إعادة تعيين كلمة المرور',
  'forgotPasswordSubtitle':
      'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.',
  'sendResetLink': 'إرسال الرابط',
  'resetLinkSent': 'إذا كان البريد مسجلاً لدينا، فسيصلك رابط إعادة التعيين.',
  'resetPasswordTitle': 'اختر كلمة مرور جديدة',
  'changePassword': 'تغيير كلمة المرور',
  'passwordChanged': 'تم تغيير كلمة المرور بنجاح.',
  'noAccount': 'ليس لديك حساب؟',
  'createAnAccount': 'إنشاء حساب',
  'staffUseWebPanel': 'يسجّل فريق سبأ الدخول من لوحة الويب، لا من التطبيق.',
  'exampleTemplate': 'مثال: {example}',
  'exPersonName': 'أحمد كريم',
  'exStreet': 'شارع 14، زقاق 7، دار 22',
  'exInstructions': 'اتصل عند وصولك إلى الجامع',
  'exTicketSubject': 'لم يصل طلبي',
  'exTicketDescription': 'الطلب SB-100003 مكتوب أنه وصل، لكن لم يصلني شيء.',
  'exReport': 'الصور لموديل مختلف',
  'exReview': 'توصيل سريع وتغليف جيد',
  'exCancel': 'طلبت المقاس الخطأ',
  'exReturn': 'وصلت الشاشة مكسورة',
  'exProductNameAr': 'سماعة لاسلكية',
  'exProductNameEn': 'Wireless earbuds',
  'exProductDescription': 'سماعات بلوتوث، بطارية 30 ساعة، مع علبة شحن.',
  'exWarranty': 'ضمان المتجر لمدة سنة',
  'exStoreName': 'Karrada Phones',
  'exStoreDescription': 'هواتف وإكسسوارات في الكرادة منذ 2015.',
  'exBusinessAddress': 'الكرادة داخل، قرب فندق بابل',
  'exDriverName': 'علي حسن',
  'exCouponCode': 'SAVE10',
  'exRepeatPassword': 'كلمة المرور نفسها مرة أخرى',
  'haveAccount': 'لديك حساب بالفعل؟',
  'createCustomerAccount': 'إنشاء حساب مشتري',
  'registerAsMerchant': 'بِع على سبأ',
  'accountType': 'نوع الحساب',
  'customer': 'مشتري',
  'merchant': 'تاجر',
  'customerAccountDescription': 'اشترِ من آلاف المتاجر',
  'merchantAccountDescription': 'افتح متجرك وابدأ البيع',
  'signOutConfirmTitle': 'تسجيل الخروج؟',
  'signOutConfirmMessage': 'ستحتاج إلى تسجيل الدخول مرة أخرى للمتابعة.',
  'merchantPendingApproval':
      'متجرك بانتظار الموافقة. يمكنك تسجيل الدخول، لكن البيع متوقف حتى توافق سبأ عليه.',
  'storeReviewAfterSignUp':
      'بعد التسجيل تراجع سبأ متجرك، وتبدأ البيع حالما توافق عليه.',

  // ------------------------------------------------------------- validation --
  'validationRequired': 'هذا الحقل مطلوب',
  'validationEmail': 'أدخل بريداً إلكترونياً صحيحاً',
  'validationPasswordLength': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
  'passwordHelper': '8 أحرف على الأقل.',
  'validationPasswordMatch': 'كلمتا المرور غير متطابقتين',
  'validationPhone': 'أدخل رقم هاتف صحيحاً',
  'validationMinLengthTemplate': 'قصير جداً. اكتب {count} على الأقل.',
  'validationNumber': 'أدخل رقماً صحيحاً',
  'validationPositive': 'أدخل قيمة أكبر من صفر',

  // --------------------------------------------------------------- navigation --
  'navHome': 'الرئيسية',
  'navCategories': 'تصفح',
  'navCart': 'السلة',
  'navOrders': 'الطلبات',
  'navAccount': 'حسابي',
  'navDashboard': 'لوحة التحكم',
  'navProducts': 'المنتجات',
  'navInventory': 'المخزون',
  'navAnalytics': 'التحليلات',

  // --------------------------------------------------------------------- home --
  'homeGreeting': 'اكتشف أفضل العروض',
  'hello': 'أهلاً',
  'introducing': 'جديدنا',
  'shopNow': 'تسوّق الآن',
  'recentSearches': 'عمليات البحث الأخيرة',
  'popularSearches': 'يبحث الناس عن',
  'searchPlaceholder': 'ابحث عن منتجات وعلامات تجارية ومتاجر',
  'flashSales': 'عروض سريعة',
  'dealsOfTheDay': 'عروض اليوم',
  'featuredProducts': 'منتجات مميزة',
  'trendingProducts': 'الأكثر رواجاً',
  'bestSellers': 'الأكثر مبيعاً',
  'newArrivals': 'وصل حديثاً',
  'recommendedForYou': 'مقترح لك',
  'allProducts': 'كل المنتجات',
  'featuredMerchants': 'متاجر مميزة',
  'popularBrands': 'علامات تجارية شهيرة',
  'endsIn': 'ينتهي خلال',

  // ------------------------------------------------------------------ catalog --
  'categories': 'الأقسام',
  'browse': 'تصفح',
  'searchProductsAndStores': 'ابحث عن منتجات ومتاجر',
  'allCategories': 'جميع الأقسام',
  'brands': 'العلامات التجارية',
  'products': 'المنتجات',
  'filters': 'التصفية',
  'sortBy': 'ترتيب حسب',
  'sortRelevance': 'الأكثر صلة',
  'sortNewest': 'الأحدث',
  'sortPriceLowHigh': 'السعر: من الأقل للأعلى',
  'sortPriceHighLow': 'السعر: من الأعلى للأقل',
  'sortBestSelling': 'الأكثر مبيعاً',
  'upTo': 'حتى',
  'noResultsFiltered': 'لا شيء يطابق كل ذلك',
  'noResultsFilteredMessage':
      'الفلاتر هي ما أفرغ هذه القائمة، لا المتجر. أزِلها لترى ما هو متاح.',
  'priceRange': 'نطاق السعر',
  'rating': 'التقييم',
  'availability': 'التوفر',
  'inStockOnly': 'المتوفر فقط',
  'onSale': 'عليه خصم',
  'gridView': 'عرض شبكي',
  'listView': 'عرض قائمة',
  // ------------------------------------------------------------------ product --
  'addToCart': 'أضف إلى السلة',
  'buyNow': 'اشترِ الآن',
  'addToWishlist': 'أضف إلى المفضلة',
  'removeFromWishlist': 'إزالة من المفضلة',
  'inStock': 'متوفر',
  'outOfStock': 'غير متوفر',
  'lowStock': 'الكمية محدودة',
  'soldBy': 'يُباع بواسطة',
  'visitStore': 'زيارة المتجر',
  'visitStoreHint': 'شاهد متجرك كما يراه المشترون',
  'sizeGuide': 'دليل المقاسات',
  'readMore': 'اقرأ المزيد',
  'readLess': 'عرض أقل',
  'description': 'الوصف',
  'warranty': 'الضمان',
  'returnPolicy': 'سياسة الإرجاع',
  'shippingInfo': 'الشحن',
  'estimatedDelivery': 'موعد التوصيل المتوقع',
  'relatedProducts': 'منتجات ذات صلة',
  'selectVariant': 'اختر أحد الخيارات',
  'selectVariantFirst': 'يرجى اختيار خيارات المنتج أولاً.',
  'addedToCart': 'تمت الإضافة إلى السلة',
  'addedToWishlist': 'تم الحفظ في المفضلة',
  'off': 'خصم',

  // --------------------------------------------------------------------- cart --
  'cart': 'السلة',
  'myCart': 'سلتي',
  'saveForLater': 'حفظ لوقت لاحق',
  'savedForLater': 'محفوظ لوقت لاحق',
  'moveToCart': 'نقل إلى السلة',
  'removeItemTitle': 'إزالة المنتج؟',
  'removeItemMessage': 'سيتم حذف هذا المنتج من سلتك.',
  'couponCode': 'رمز الخصم',
  'applyCoupon': 'تطبيق',
  'couponApplied': 'تم تطبيق رمز الخصم',
  'couponsForYou': 'كوبونات لك',
  'amountOffTemplate': 'خصم {amount}',
  'firstOrderOnly': 'لطلبك الأول فقط',
  'onAnyOrder': 'على أي طلب',
  'onOrdersOver': 'للطلبات فوق',
  'couponCopied': 'تم نسخ الرمز. ستجده أيضاً في سلتك.',
  'tapCouponToUse': 'كوبوناتك - اضغط على واحد لاستخدامه',
  'removeCoupon': 'إزالة رمز الخصم',
  'shipping': 'الشحن',
  'tax': 'الضريبة',
  'discount': 'الخصم',
  'storeSubtotal': 'مجموع المتجر',
  'freeShipping': 'مجاني',
  'totalNote': 'مجموع واحد لكل ما في سلتك',
  'fromWord': 'من',
  'eachStoreShips': 'كل متجر يشحن بنفسه.',
  'deliveryFee': 'رسوم التوصيل',
  'grandTotal': 'الإجمالي',
  'proceedToCheckout': 'إتمام الشراء',
  'itemsFromStore': 'منتجات من هذا المتجر',
  'maxQuantityReached': 'لقد وصلت إلى الحد الأقصى للكمية لهذا المنتج.',

  // ----------------------------------------------------------------- checkout --
  'checkout': 'إتمام الشراء',
  'deliverTo': 'التوصيل إلى',
  'change': 'تغيير',
  'changeAddress': 'تغيير العنوان',
  'noDelivery': 'لا توصيل هنا',
  'delivery': 'التوصيل',
  'deliveryWord': 'توصيل',
  'twoDeliveriesNote': 'كل متجر يرسل طرده بنفسه، لذا قد تصل في أيام مختلفة.',
  'codNote': 'ادفع نقداً عند وصول طلبك. لا يُخصم شيء الآن.',
  'deliveryAddress': 'عنوان التوصيل',
  'selectAddress': 'اختر عنواناً',
  'addAddress': 'إضافة عنوان',
  'editAddress': 'تعديل العنوان',
  'defaultAddress': 'العنوان الافتراضي',
  'setAsDefault': 'تعيين كافتراضي',
  'shippingMethod': 'طريقة الشحن',
  'paymentMethod': 'طريقة الدفع',
  'orderReview': 'مراجعة الطلب',
  'placeOrder': 'تأكيد الطلب',
  'orderPlaced': 'تم إنشاء الطلب',
  'orderPlacedMessage': 'شكراً لك. تم استلام طلبك.',
  'viewOrder': 'عرض الطلب',
  'continueShopping': 'متابعة التسوق',
  'deliveryInstructions': 'تعليمات التوصيل',
  'cashOnDelivery': 'الدفع عند الاستلام',
  'card': 'بطاقة ائتمان أو خصم',
  'wallet': 'محفظة إلكترونية',
  'bankTransfer': 'تحويل بنكي',
  'totalsRecalculated':
      'يتم احتساب الإجمالي على الخادم وقد يختلف عن التقدير المعروض.',

  // ------------------------------------------------------------------ address --
  'addresses': 'العناوين',
  'state': 'المحافظة',
  'district': 'الحي',
  'street': 'الشارع',
  'building': 'المبنى',
  'apartment': 'الشقة',
  'postalCode': 'الرمز البريدي',
  'deleteAddressTitle': 'حذف العنوان؟',
  'deleteAddressMessage': 'سيتم حذف هذا العنوان نهائياً.',

  // ------------------------------------------------------------------- orders --
  'orders': 'الطلبات',
  'myOrders': 'طلباتي',
  'orderNumber': 'رقم الطلب',
  'orderDate': 'تاريخ الطلب',
  'orderTimeline': 'مراحل الطلب',
  'orderItems': 'المنتجات',
  'orderDetails': 'تفاصيل الطلب',
  'notAvailable': 'غير متوفر',
  'invoice': 'الفاتورة',
  'cancelOrder': 'إلغاء الطلب',
  'cancelOrderTitle': 'إلغاء هذا الطلب؟',
  'cancelOrderMessage': 'لا يمكن التراجع عن هذا الإجراء.',
  'requestReturn': 'طلب إرجاع',
  'returnReason': 'السبب',
  'orderStatusAll': 'الكل',
  'orderStatusPending': 'قيد الانتظار',
  'orderStatusConfirmed': 'مؤكد',
  'orderStatusProcessing': 'قيد التجهيز',
  'stepPreparing': 'قيد التجهيز',
  'expectedArrivalTemplate': 'الوصول المتوقع: {time}',
  'orderFollowsSlowestTemplate': 'يُظهر الطلب خطوة المتجر الأبطأ: {status}.',
  'orderStatusShipped': 'تم الشحن',
  'orderStatusDelivered': 'تم التسليم',
  'orderStatusCancelled': 'ملغي',
  'orderStatusReturned': 'مُرتجع',
  'orderStatusRefunded': 'تم الاسترداد',
  'paymentStatus': 'الدفع',
  'deliveryStatus': 'التوصيل',

  // ------------------------------------------------------------------ account --
  'account': 'حسابي',
  'myProfile': 'ملفي الشخصي',
  'editProfile': 'تعديل الملف الشخصي',
  'wishlist': 'المفضلة',
  'notifications': 'الإشعارات',
  'messages': 'الرسائل',
  'support': 'الدعم',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'theme': 'المظهر',
  'themeSystem': 'حسب النظام',
  'themeLight': 'فاتح',
  'themeDark': 'داكن',
  'deleteAccount': 'حذف الحساب',
  'deleteAccountTitle': 'حذف حسابك؟',
  'deleteAccountMessage': 'سيتم حذف حسابك نهائياً ولا يمكن التراجع عن ذلك.',
  'profileUpdated': 'تم تحديث الملف الشخصي',
  'guestTitle': 'لم تسجّل الدخول',
  'guestMessage': 'سجّل الدخول لعرض طلباتك ومفضلتك وحسابك.',

  // ----------------------------------------------------------------- merchant --
  'merchantDashboard': 'لوحة التحكم',
  'myStore': 'متجري',
  'todaySales': 'اليوم',
  'totalSales': 'إجمالي المبيعات',
  'revenue': 'الإيرادات',
  'pendingOrders': 'طلبات قيد الانتظار',
  'lowStockItems': 'مخزون منخفض',
  'outOfStockItems': 'نفد المخزون',
  'totalProducts': 'المنتجات',
  'totalOrders': 'الطلبات',
  'topProducts': 'أفضل المنتجات',
  'myProducts': 'منتجاتي',
  'addProduct': 'إضافة منتج',
  'editProduct': 'تعديل المنتج',
  'productName': 'اسم المنتج',
  'sku': 'رمز المنتج',
  'barcode': 'الباركود',
  'stock': 'المخزون',
  'originalPrice': 'السعر قبل الخصم',
  'saveDraft': 'حفظ كمسودة',
  'submitForApproval': 'إرسال للمراجعة',
  'productDraft': 'مسودة',
  'productPendingApproval': 'بانتظار الموافقة',
  'productApproved': 'معتمد',
  'productRejected': 'مرفوض',
  'inventory': 'المخزون',
  'adjustStock': 'تعديل المخزون',
  'availableStock': 'المتاح',
  'reservedStock': 'المحجوز',
  'soldStock': 'المُباع',
  'lowStockThreshold': 'حد المخزون المنخفض',
  'merchantOrders': 'طلبات المتجر',
  'updateOrderStatus': 'تحديث الحالة',
  'analytics': 'التحليلات',
  'payouts': 'التسويات المالية',
  'grossSales': 'إجمالي المبيعات',
  'commission': 'عمولة المنصة',
  'netEarnings': 'صافي الأرباح',
  'pendingPayout': 'قيد التحويل',
  'availablePayout': 'المتاح للتحويل',
  'averageOrderValue': 'متوسط قيمة الطلب',
  'storeSettings': 'إعدادات المتجر',
  'storeName': 'اسم المتجر',
  'storeDescription': 'وصف المتجر',
  'businessType': 'نوع النشاط',
  'businessAddress': 'عنوان النشاط',

  // ------------------------------------------------------------------ support --
  'supportTickets': 'تذاكر الدعم',
  'newTicket': 'تذكرة جديدة',
  'ticketSubject': 'الموضوع',
  'ticketCategory': 'التصنيف',
  'ticketDescription': 'اشرح المشكلة',
  'ticketStatusOpen': 'مفتوحة',
  'ticketStatusInProgress': 'قيد المعالجة',
  'ticketStatusWaiting': 'بانتظار ردك',
  'ticketStatusResolved': 'تم الحل',
  'ticketStatusClosed': 'مغلقة',
  'typeMessage': 'اكتب رسالة',
  'send': 'إرسال',
  'photo': 'صورة',
  'sendPhoto': 'إرسال صورة',
  'photoDeleted': 'حُذفت الصورة',
  'photoRemovedBySaba': 'أزالت سبأ الصورة',

  // ------------------------------------------------------------ notifications --
  'markAllRead': 'تعليم الكل كمقروء',

  // ----------------------------------------------------------------- misc --
  'or': 'أو',
  'all': 'الكل',
  'update': 'تحديث',
  'create': 'إنشاء',
  'reset': 'إعادة تعيين',
  'viewDetails': 'عرض التفاصيل',
  'saveChanges': 'حفظ التغييرات',
  'stores': 'المتاجر',
  'store': 'المتجر',
  'signInRequired': 'يلزم تسجيل الدخول',
  'signInToContinue': 'سجّل الدخول للمتابعة',
  'orderSummary': 'ملخص الطلب',
  'shippingAddress': 'عنوان الشحن',
  'trackOrder': 'تتبع الطلب',
  'selectCountry': 'اختر الدولة',
  'selectCity': 'اختر المدينة',
  'statusApproved': 'معتمد',
  'statusRejected': 'مرفوض',
  'statusSuspended': 'موقوف',
  'statusActive': 'نشط',
  'statusInactive': 'غير نشط',
  'attachments': 'المرفقات',
  'sortAndFilter': 'الترتيب والتصفية',
  'noImage': 'لا توجد صورة',
  'salesChart': 'المبيعات',
  'thisWeek': 'هذا الأسبوع',
  'thisMonth': 'هذا الشهر',
  'thisYear': 'هذه السنة',
  'today': 'اليوم',
  // -------------------------------------------------------- merchant extra --
  'refunds': 'المبالغ المستردة',
  'returns': 'المرتجعات',
  'cancellations': 'الإلغاءات',
  'productsSold': 'المنتجات المباعة',
  'customers': 'العملاء',
  'orderStatusNew': 'جديد',
  'requestPayout': 'طلب تحويل',
  'payoutHistory': 'سجل التحويلات',
  'noPayouts': 'لا توجد تحويلات بعد',
  'stockAdjustment': 'تعديل المخزون',
  'newQuantity': 'الكمية الجديدة',
  'reason': 'السبب',
  'searchProducts': 'ابحث في منتجاتك',
  'period': 'الفترة',
  'noProductsYet': 'لا توجد لديك منتجات بعد',
  'addFirstProduct': 'أضف أول منتج لك',
  'deleteProductTitle': 'حذف المنتج؟',
  'deleteProductMessage': 'سيتم حذف هذا المنتج من متجرك.',
  'category': 'القسم',
  'selectCategory': 'اختر القسم',
  'brand': 'العلامة التجارية',
  'brandHint': 'اكتب العلامة التجارية أو اخترها',
  'brandHelp': 'العلامة غير الموجودة في القائمة تراجعها سبأ مع المنتج.',
  'markAsShipped': 'تحديد كمشحون',
  'nextStatus': 'الحالة التالية',
  'customerName': 'العميل',
  'noStoreYet': 'لا يوجد متجر',
  // ------------------------------------------------------------------ media --
  'addPhotos': 'إضافة صور',
  'addPhoto': 'إضافة صورة',
  'takePhoto': 'التقاط صورة',
  'chooseFromGallery': 'الاختيار من المعرض',
  'attachFile': 'إرفاق ملف',
  'uploading': 'جارٍ الرفع',
  'uploadFailed': 'فشل الرفع',
  'retryUpload': 'إعادة محاولة الرفع',
  'cancelUpload': 'إلغاء الرفع',
  'removeFile': 'إزالة الملف',
  'setAsPrimary': 'تعيين كصورة رئيسية',
  'primaryImage': 'الصورة الرئيسية',
  'noFilesSelected': 'لم يتم اختيار أي ملف',
  'maxFilesReached': 'هذا أقصى ما يمكنك إضافته هنا.',
  'mediaTooLarge': 'حجم هذا الملف كبير جداً',
  'mediaUnsupportedType': 'نوع هذا الملف غير مدعوم',
  'mediaUnsupportedExtension': 'امتداد هذا الملف غير مدعوم',
  'mediaImageTooSmall': 'أبعاد هذه الصورة صغيرة جداً',
  'mediaImageTooLarge': 'أبعاد هذه الصورة كبيرة جداً',
  'mediaUnreadable': 'تعذّرت قراءة هذا الملف',
  'someFilesRejected': 'لم تتم إضافة بعض الملفات',
  'paymentPending': 'الدفع قيد الانتظار',
  'paymentPendingMessage': 'لم نستلم تأكيداً من مزوّد الدفع حتى الآن.',
  'paymentConfirmed': 'تم تأكيد الدفع',
  'paymentFailedTitle': 'لم تكتمل عملية الدفع',
  'paymentFailedMessage':
      'لم تتم عملية الدفع ولم يُخصم أي مبلغ. أعد تقديم الطلب، أو اطلب المساعدة من الدعم.',
  'checkPaymentStatus': 'التحقق من حالة الدفع',
  'awaitingPayment': 'بانتظار الدفع',

  // ------------------------------------------- merchant product media --
  'productImages': 'صور المنتج',
  'productImagesHint':
      'الصورة الأولى هي الرئيسية. اضغط على صورة أخرى لتصبح الرئيسية.',
  'productBasics': 'المعلومات الأساسية',
  'priceAndStock': 'السعر والمخزون',
  'productCodes': 'رمز المنتج والباركود',
  'productPolicies': 'الضمان والإرجاع',
  'variants': 'الخيارات',
  'variantsHint':
      'أضف خيارات مثل اللون أو السعة. كل تركيبة تصبح خياراً له سعره ومخزونه.',
  'addOption': 'إضافة خيار',
  'editOption': 'تعديل الخيار',
  'optionName': 'اسم الخيار',
  'optionNameHint': 'اللون، المقاس، السعة…',
  'optionValues': 'القيم',
  'optionValuesHint': 'أحمر، أزرق، أخضر (افصل بفاصلة)',
  'inheritPrice': 'نفس سعر المنتج',

  // ------------------------------------------- returns, refunds, invoice --
  'myReturns': 'مرتجعاتي',
  'noReturns': 'لا توجد مرتجعات',
  'noReturnsMessage': 'ستظهر هنا طلبات الإرجاع مع حالة استرداد المبلغ.',
  'returnStatusRequested': 'تم الطلب',
  'returnStatusApproved': 'تمت الموافقة',
  'returnStatusRejected': 'مرفوض',
  'returnStatusPickup': 'تم جدولة الاستلام',
  'returnStatusReceived': 'تم الاستلام',
  'returnStatusRefundPending': 'الاسترداد قيد الانتظار',
  'returnStatusRefunded': 'تم الاسترداد',
  'returnStatusClosed': 'مغلق',
  'returnDetails': 'تفاصيل الإرجاع',
  'returnedItems': 'المنتجات المرتجعة',
  'returnRequestedOn': 'تاريخ الطلب',
  'returnPhotos': 'الصور',
  'rejectionReason': 'سبب الرفض',
  'returnProgress': 'التقدم',
  'refund': 'الاسترداد',
  'refundStatus': 'حالة الاسترداد',
  'refundAmount': 'مبلغ الاسترداد',
  'refundMethod': 'تم الاسترداد إلى',
  'refundReference': 'الرقم المرجعي',
  'refundProcessedOn': 'تمت المعالجة في',
  'refundExpectedBy': 'متوقع بحلول',
  'refundStatusPending': 'قيد الانتظار',
  'refundStatusProcessing': 'قيد المعالجة',
  'refundStatusCompleted': 'مكتمل',
  'refundStatusFailed': 'فشل',
  'noRefundYet': 'لم يتم إصدار استرداد لهذا الطلب بعد.',
  'viewInvoice': 'عرض الفاتورة',
  'invoiceNumber': 'رقم الفاتورة',
  'issuedOn': 'تاريخ الإصدار',
  'billedTo': 'الفاتورة إلى',
  'unitPrice': 'سعر الوحدة',
  'amount': 'المبلغ',
  'downloadInvoice': 'تنزيل PDF',
  'invoiceTotals': 'الإجماليات',
  'amountPaid': 'المبلغ المدفوع',
  'cancelReason': 'سبب الإلغاء',
  'selectCancelReason': 'لماذا تريد الإلغاء؟',
  'cancelReasonChangedMind': 'غيّرت رأيي',
  'cancelReasonFoundCheaper': 'وجدته بسعر أقل في مكان آخر',
  'cancelReasonDeliveryTooSlow': 'التوصيل يستغرق وقتاً طويلاً',
  'cancelReasonOrderedByMistake': 'طلبته عن طريق الخطأ',
  'cancelReasonOther': 'سبب آخر',
  'cancelReasonNote': 'أخبرنا المزيد',
  'cancelReasonRequired': 'يرجى اختيار سبب',

  // ------------------------------------------------- after the sale --
  'returnReasonDamaged': 'وصل تالفاً',
  'returnReasonWrongItem': 'وصل منتج خاطئ',
  'returnReasonNotAsDescribed': 'لا يطابق الوصف',
  'returnReasonMissingParts': 'هناك أجزاء ناقصة',
  'returnReasonChangedMind': 'غيّرت رأيي',
  'returnReasonOther': 'سبب آخر',
  'emptyFilteredList': 'لا شيء ضمن هذا التصنيف',
  'emptyFilteredListMessage':
      'لا يوجد لديك شيء في هذه الحالة حالياً. كل ما عدا ذلك ما زال ضمن «الكل».',
  'showAll': 'عرض الكل',
  'ticketCategoryOrder': 'مشكلة في طلب',
  'ticketCategoryPayment': 'الدفع أو الفوترة',
  'ticketCategoryDelivery': 'التوصيل أو الشحن',
  'ticketCategoryReturn': 'إرجاع أو استرداد',
  'ticketCategoryProduct': 'سؤال عن منتج',
  'ticketCategoryAccount': 'حسابي',
  'ticketCategoryOther': 'شيء آخر',
  'emptyTicketsMessage': 'افتح تذكرة وسيرد عليك الدعم هنا.',
  'emptyProductsMessage': 'لا يوجد لدى هذا المتجر أي منتج حالياً.',
  'emptyNotificationsMessage':
      'تصل هنا تحديثات الطلبات والردود وانخفاض الأسعار.',
  'addressNickname': 'سمِّ هذا العنوان',
  'addressNicknameHint': 'المنزل، العمل، بيت أمي',
  'addressWho': 'لمن هو',
  'addressWhere': 'أين يُوصَّل',
  'addressExtras': 'أي شيء آخر',
  'emptyAddressesMessage':
      'أضف عنواناً وسيظهر عند إتمام الطلب، فتكتبه مرة واحدة فقط.',
  'languageSystem': 'حسب إعدادات الجهاز',
  'languageSystemHint': 'يستخدم سبأ اللغة المضبوطة على هاتفك.',
  'noReviewsMessage': 'كن أول من يقيّم هذا المنتج.',
  'merchantReplied': 'رد البائع',
  'reportReview': 'الإبلاغ عن التقييم',
  'report': 'إبلاغ',
  'reportProduct': 'الإبلاغ عن المنتج',
  'reportStore': 'الإبلاغ عن المتجر',
  'reportChat': 'الإبلاغ عن المحادثة',
  'reportThanks': 'شكرًا. ستنظر سبأ في الأمر.',
  'block': 'حظر',
  'unblock': 'إلغاء الحظر',
  'blockTitle': 'حظر هذه المحادثة؟',
  'blockMessage':
      'لن يتمكن أحد من الكتابة هنا حتى تلغي الحظر. تبقى المحادثة مقروءة، '
      'والطلبات تستمر كما هي.',
  'chatBlockedByMe': 'حظرت هذه المحادثة، فلا يمكن لأحد الكتابة هنا.',
  'chatBlocked': 'الرسائل متوقفة في هذه المحادثة.',
  'storeReviews': 'تقييمات المتجر',
  'reportReasonLabel': 'ما سبب الإبلاغ؟',
  'reportCounterfeit': 'منتج مقلّد',
  'reportProhibited': 'منتج محظور',
  'reportMisleading': 'وصف أو صور مضللة',
  'reportOffensive': 'محتوى مسيء',
  'reportSpam': 'رسائل مزعجة',
  'reportOther': 'سبب آخر',
  'reportDetails': 'أخبرنا المزيد',
  'reportSubmitted': 'شكراً لك. سيراجع فريقنا هذا البلاغ.',
  'reportReasonRequired': 'يرجى اختيار سبب',
  'noReviews': 'لا توجد تقييمات بعد',
  'clearHistoryTitle': 'مسح سجل البحث؟',
  'clearHistoryMessage': 'ستُزال عمليات البحث الأخيرة من هذا الجهاز ومن حسابك.',
  'noMessagesYet': 'لا توجد رسائل بعد',
  'noMessagesYetMessage': 'اسأل عن منتج أو طلب أو التوصيل، وسيظهر الرد هنا.',
  'selectItemsToReturn': 'اختر منتجاً واحداً على الأقل لإرجاعه.',
  'removeOptionTitle': 'إزالة هذا الخيار؟',
  'removeOptionMessage':
      'ستُحذف صفوف الخيارات التي أنشأها، ومعها رمز المنتج والسعر والمخزون المُدخلة فيها.',
  'variantsKeptIfEmpty':
      'يتم الإبقاء على الخيارات الحالية ما دام هذا فارغاً. أضف خياراً لاستبدالها.',
  'waitForUploads': 'انتظر حتى ينتهي رفع الصور.',
  'keepOrder': 'الإبقاء على الطلب',
  'storeUpdated': 'تم تحديث المتجر',
  'moreOptions': 'خيارات أخرى',
  'verified': 'مُؤكَّد',

  // ---------------------------------------------- merchant dashboard --
  'revenueThisMonth': 'إيرادات هذا الشهر',
  'needsYouToday': 'يحتاج انتباهك اليوم',
  'oldestWaiting': 'أقدمها ينتظر منذ',
  'stillListedNotBuyable': 'تبقى معروضة لكن لا يمكن شراؤها',
  'replyWithin': 'الرد خلال',
  'ordersThisMonth': 'الطلبات هذا الشهر',
  'storeRating': 'تقييم المتجر',
  'vsLastMonth': 'عن الشهر الماضي',
  'previousPeriod': 'الفترة السابقة',
  'lastMonthSame': 'الشهر الماضي، نفس',
  'noSalesYet': 'لا مبيعات في هذه الفترة',
  'storeOpen': 'المتجر مفتوح',
  'storeClosed': 'المتجر مغلق',
  'allCaughtUp': 'لا شيء يحتاج انتباهك الآن',
  'viewAll': 'عرض الكل',

  // ------------------------------------------------- merchant orders --
  'toConfirm': 'بانتظار التأكيد',
  'preparing': 'قيد التجهيز',
  'decline': 'رفض',
  'whyDeclining': 'ما سبب الرفض؟',
  'declineNote':
      'الرفض يتطلب سبباً ويلغي الطلب. لم يُدفع شيء، فلا شيء يُعاد. كل رفض يؤثر على تقييم متجرك.',
  'reasonOutOfStock': 'نفد من المخزون',
  'reasonCannotFulfil': 'لا يمكن التجهيز في الوقت المحدد',
  'reasonAddressProblem': 'مشكلة في العنوان',
  'reasonCustomerAsked': 'المشتري طلب الإلغاء',
  'orderDeclined': 'تم رفض الطلب. تم إبلاغ المشتري.',

  // ----------------------------------------------- merchant products --
  'searchYourProducts': 'ابحث في منتجاتك',
  'lowStockFilter': 'مخزون منخفض',
  'outFilter': 'نفد',
  'hiddenFilter': 'مخفي',
  'hidden': 'مخفي',
  'hideFromShoppers': 'إخفاء عن المشترين',
  'showToShoppers': 'إظهار للمشترين',
  'productHidden': 'تم الإخفاء. لم يعد المشترون يرونه.',
  'productShown': 'تم الإظهار. يمكن للمشترين شراؤه مجدداً.',
  'inStockCount': 'في المخزون',
  'leftCount': 'متبقي',
  'restock': 'إعادة التخزين',
  'setStock': 'تحديد المخزون',
  'flashSale': 'عرض سريع',
  'flashSaleUntilTemplate': 'عرض سريع حتى {time}',
  'salePrice': 'سعر العرض',
  'normalPriceTemplate': 'السعر العادي {price}.',
  'salePriceInvalid': 'أدخل سعر العرض.',
  'salePriceNotLower': 'يجب أن يكون سعر العرض أقل من السعر العادي.',
  'endSaleQuestion': 'إنهاء هذا العرض السريع الآن؟',
  'endSaleWarning': 'يعود المتسوقون إلى دفع السعر العادي فوراً.',
  'saleEndPassed': 'اختر وقت انتهاء لم يمضِ بعد.',
  'startSale': 'ابدأ العرض',
  'endSaleNow': 'أنهِ العرض الآن',
  'flashSaleSaved': 'تم حفظ العرض السريع.',
  'flashSaleEnded': 'انتهى العرض السريع.',
  'noProductsMatch': 'لا توجد منتجات مطابقة',
  'productsRejected': 'منتجات تحتاج تعديلاً',
  'rejectedNeedsEdit': 'لم تتم الموافقة عليها وهي غير معروضة للبيع',

  // ------------------------------------------- entry and onboarding --
  'sabaTagline': 'سوق العراق. متاجر كثيرة، سلة واحدة.',
  'chooseYourLanguage': 'اختر لغتك',
  'changeLanguageLater': 'يمكنك تغييرها لاحقاً من الحساب.',
  'englishName': 'English',
  'englishOther': 'الإنجليزية',
  'arabicName': 'العربية',
  'arabicOther': 'Arabic',
  'alreadyHaveAccount': 'لديك حساب بالفعل؟',
  'whatsYourNumber': "ما رقم هاتفك؟",
  'phoneStepCustomerMessage':
      "سنرسل لك رمزاً من 6 أرقام برسالة. على هذا الرقم يتصل بك المتجر بخصوص طلبك.",
  'phoneStepMerchantMessage':
      "سنرسل لك رمزاً من 6 أرقام برسالة. على هذا الرقم يتصل بك الزبائن وسبأ بخصوص متجرك.",
  'sendCode': "أرسل الرمز",
  'enterTheCode': "أدخل الرمز",
  'codeSentTo': "أُرسل الرمز إلى",
  'verificationCode': "رمز التحقق",
  'changeNumber': "تغيير الرقم",
  'didNotGetCode': "لم يصلك الرمز؟",
  'resendCode': "إعادة الإرسال",
  'codeSentAgain': "تم إرسال رمز جديد.",
  'demoCodeNote': "نسخة تجريبية، لا تُرسَل رسالة. رمزك هو",
  'validationOtpLength': "أدخل الأرقام الستة كاملة.",
  'verify': "تحقق",
  'verifyNumberTitle': "تأكيد رقمك",
  'verifyNumberWhy': "تحتاج سبأ إلى تأكيد رقمك مرة واحدة. أدخل الرمز الذي أرسلناه.",
  'verifyNumberToSignIn':
      "تحتاج سبأ إلى تأكيد رقمك مرة واحدة. اطلب رمزاً ثم سجّل الدخول به.",
  'numberVerified': "تم التحقق من الرقم",
  'businessTypeIndividual': "فرد",
  'businessTypeSoleProprietorship': "مؤسسة فردية",
  'businessTypeCompany': "شركة",
  'businessTypeDistributor': "موزّع",
  'demoAccountsTitle': "حسابات تجريبية",
  'demoAccountsNote': "اضغط على أحدها لتعبئة الحقول. أي كلمة مرور تعمل.",
  'demoShopper': "مشترٍ",
  'demoMerchant': "بائع",
  'yourProfile': "ملفك الشخصي",
  'yourProfileSubtitle': "أخبرنا قليلاً عن نفسك.",
  'yourStore': "متجرك",
  'yourStoreSubtitle': "هذا ما سيراه المشترون.",
  'storeSignUpSubtitle':
      "اسمك واسم متجرك ومدينته. البقية لاحقاً من إعدادات المتجر.",
  'stepWord': "الخطوة",
  'ofWord': "من",
  'chooseBusinessType': "اختر نوع النشاط",
  'changeLanguage': "تغيير اللغة",
  'accountYou': "حسابك",
  'accountGetHelp': "المساعدة",
  'accountSecurity': "الأمان والإعدادات",
  'itemRemoved': 'أُزيل من السلة',
  'undo': 'تراجع',
  'removeUnavailable': 'إزالة العناصر غير المتوفرة',
  'searchInStore': 'ابحث في هذا المتجر',
  'noResultsInStore': 'لا شيء في هذا المتجر يطابق بحثك',
  'noResultsInStoreMessage':
      'بحثك هو ما أفرغ هذه القائمة، لا المتجر. امسحه لترى كل ما هنا.',
  'copiedToClipboard': 'تم النسخ',
  'copy': 'نسخ',
  'makeMainImage': 'استخدامها كصورة رئيسية',
  'message': 'مراسلة',
  'emptyConversationsHint':
      'لتسأل متجراً عن شيء، اضغط «مراسلة» في صفحة المنتج أو المتجر أو الطلب.',
  'emptyConversationsStoreHint': 'عندما يراسل زبون متجرك، تظهر رسالته هنا.',
  'aboutTopicTemplate': 'بخصوص {topic}: ',
  'aboutOrderTemplate': 'بخصوص الطلب {number}: ',
  'codPlacedMessage': 'جهّز المبلغ نقداً: تدفع عند وصول الطلب.',
  'payOnDelivery': 'الدفع عند الاستلام',
  'paymentPaid': 'مدفوع',
  'paymentFailedShort': 'فشل الدفع',
  'coupons': 'القسائم',
  'couponsTileHint': 'رموز خصم لزبائنك',
  'newCoupon': 'قسيمة جديدة',
  'editCoupon': 'تعديل القسيمة',
  'couponCodeHelper': 'من 3 إلى 15 حرفاً أو رقماً. يكتبه الزبون أو يضغط عليه.',
  'suggestCode': 'اقتراح',
  'discountPercent': 'نسبة مئوية',
  'discountAmountIqd': 'مبلغ (د.ع)',
  'discountLabel': 'الخصم',
  'minimumOrderOptional': 'الحد الأدنى للطلب',
  'minimumOrderHelper': 'يُحسب على ما يُشترى من متجرك.',
  'startsOn': 'يبدأ',
  'endsOn': 'ينتهي',
  'noEndDate': 'بلا تاريخ انتهاء',
  'usageLimitOptional': 'عدد مرات الاستخدام',
  'usageLimitHelper': 'اتركه فارغاً لعدد غير محدود.',
  'couponUsedTemplate': 'استُخدمت {times}',
  'couponUsedOfTemplate': 'استُخدمت {used} من {limit}',
  'couponScheduled': 'مجدولة',
  'couponPaused': 'متوقفة',
  'couponEnded': 'منتهية',
  'couponUsedUp': 'نفدت',
  'untilDateTemplate': 'حتى {date}',
  'startsDateTemplate': 'تبدأ {date}',
  'pauseCoupon': 'إيقاف مؤقت',
  'resumeCoupon': 'استئناف',
  'deleteCouponQuestion': 'حذف هذه القسيمة؟',
  'deleteCouponMessage': 'لن يتمكن الزبائن من استخدامها بعد الآن.',
  'couponSaved': 'تم حفظ القسيمة',
  'couponDeleted': 'تم حذف القسيمة',
  'noCouponsYet': 'لا توجد قسائم بعد',
  'noCouponsYetMessage':
      'أنشئ رمز خصم لمتجرك. يراه الزبائن في صفحة متجرك وفي الرئيسية وفي سلتهم.',
  'couponPreview': 'كيف يراها الزبائن',
  'couponsFromTemplate': 'قسائم من {store}',
  'atStoreTemplate': 'في {store}',
  'couponCodeInvalid': 'استخدم من 3 إلى 15 حرفاً أو رقماً.',
  'discountInvalid': 'أدخل خصماً أكبر من 0.',
  'percentTooHigh': 'لا يمكن أن تزيد النسبة على 90.',
  'endBeforeStart': 'يجب أن يكون تاريخ الانتهاء بعد البداية.',
  'wholeNumber': 'أدخل عدداً صحيحاً.',
  'yesterday': 'أمس',
  'deleteStoreAccountHint':
      'يُغلق متجرك الآن. يُحذف بعد انتهاء طلباتك ومرتجعاتك وآخر فاتورة.',
  'deleteStoreAccountTitle': 'حذف حساب متجرك؟',
  'deleteStoreAccountMessage':
      'يُغلق متجرك الآن ولا يستقبل طلبات جديدة.\n\n'
      'يُحذف حسابك وبياناتك الشخصية بعد أن تنتهي طلباتك المفتوحة، وتمضي مدة '
      'الإرجاع (7 أيام بعد آخر توصيل)، وتُدفع آخر فاتورة. هذه الفاتورة عن '
      'شهر آخر توصيل وتُستحق عند نهاية ذلك الشهر، فيستغرق الحذف حتى نهايته '
      'على الأقل. سنرسل لك رسالة نصية عند اكتمال الحذف. وإذا بقيت فاتورة غير '
      'مدفوعة فلا يُحذف حسابك.\n\n'
      'تبقى الطلبات والفواتير والمرتجعات وفواتير سبأ الشهرية كسجلات، كما '
      'يطلب القانون.',
  'storeDeletionTitle': 'يجري حذف حسابك',
  'storeDeletionAskedTemplate': 'طُلب في {date}. متجرك مغلق.',
  'storeDeletionWaitsFor': 'يُحذف عندما لا يبقى شيء مما يلي:',
  'stillOpenOrdersTemplate': 'طلبات ما زالت مفتوحة: {count}',
  'openReturnsTemplate': 'مرتجعات تنتظر التسوية: {count}',
  'stillOwedTemplate': 'المستحق لسبأ: {amount}',
  'returnsOpenUntilTemplate': 'الإرجاع مفتوح حتى {date}',
  'storeDeletionSoon': 'لم يبقَ شيء مفتوح: سيُحذف خلال ساعة.',
  'storeDeletionSms': 'سنرسل لك رسالة نصية عند اكتمال الحذف.',
  'storeDeletionUnpaid': 'إذا بقيت فاتورة غير مدفوعة فلا يُحذف حسابك.',
  'keepMyAccount': 'الإبقاء على حسابي',
  'keepMyAccountTitle': 'الإبقاء على حسابك؟',
  'keepMyAccountMessage':
      'لن يُحذف حسابك. يبقى متجرك مغلقاً حتى تفتحه من لوحة التحكم.',
  'accountKept': 'لن يُحذف حسابك.',
  'storeBeingDeleted': 'مغلق: يجري حذف الحساب',
  'deleteAccountHint': 'يحذف حسابك وبياناتك المحفوظة. لا يمكن التراجع عن ذلك.',
  'yourCity': 'مدينتك',
  'chooseYourCity': 'اختر مدينتك',
  'deliverToTemplate': 'التوصيل إلى {city}',
  'cityRequired': 'اختر المدينة.',
  'useEmailInstead': 'استخدم البريد الإلكتروني بدلاً من ذلك',
  'usePhoneInstead': 'استخدم رقم الهاتف بدلاً من ذلك',
  'emailOptional': 'البريد الإلكتروني',
  'forgotPasswordPhoneSubtitle': 'أدخل رقم هاتفك وسنرسل لك رمزاً برسالة نصية.',
  'saveNewPassword': 'احفظ كلمة المرور الجديدة',
  'phoneSignInHelper': 'تسجّل الدخول بهذا الرقم. لتغييره تواصل مع الدعم.',
  'area': 'المنطقة أو الحي',
  'areaHint': 'مثل: المنصور',
  'nearestLandmark': 'أقرب نقطة دالة',
  'nearestLandmarkHint': 'مثل: قرب جامع الرشيد',
  'streetAndHouse': 'الشارع والزقاق ورقم الدار',
  'driverCallsThisNumber': 'يتصل بك المندوب على هذا الرقم وهو في الطريق.',
  'cashToEachDriver': 'المبلغ نقداً لكل مندوب',
  'cashToEachDriverNote': 'يستلم مندوب كل متجر مبلغ ذلك المتجر فقط.',
  'cashToDriver': 'نقداً للمندوب',
  'paidToDriver': 'دُفع للمندوب',
  'collectInCash': 'استلم نقداً',
  'iqdSteps': 'استخدم مضاعفات 250 د.ع، مثل 12,250 أو 12,500.',
  'deliverySameDay': 'في نفس اليوم',
  'delivery1to2Days': '1–2 يوم',
  'delivery2to3Days': '2–3 أيام',
  'delivery3to5Days': '3–5 أيام',
  'delivery5to7Days': '5–7 أيام',
  'noDeliveryToTemplate': 'لا يوصّل إلى {city}',
  'deliversToTemplate': 'يوصّل إلى {city}',
  'addressCityNoteTemplate':
      'مدينتك في الرئيسية {home}. هذا الطلب يذهب إلى {city} حيث العنوان.',
  'deliverySettings': 'التوصيل',
  'whereYouDeliver': 'أين توصّل',
  'wholeIraq': 'كل العراق',
  'onlyMyCity': 'مدينتي فقط',
  'feeInYourCity': 'الأجرة داخل مدينتك',
  'feeOtherCities': 'الأجرة إلى المدن الأخرى',
  'timeInYourCity': 'المدة داخل مدينتك',
  'timeOtherCities': 'المدة إلى المدن الأخرى',
  'zeroIsFree': 'اكتب 0 للتوصيل المجاني.',
  'removeOrChangeAddress': 'احذف منتجاته من السلة أو اختر عنواناً آخر.',
  'chooseDeliveryTime': 'اختر المدة',
  'call': 'اتصال',
  'orderStatusRefused': 'رُفض عند الاستلام',
  'callShopperFirst': 'اتصل بالمشتري أولاً لتتأكد من الطلب والعنوان.',
  'iCalledConfirm': 'اتصلت به: تأكيد',
  'whoDelivers': 'من يوصّل الطلب؟',
  'driverName': 'اسم المندوب',
  'courierPhone': 'رقم هاتفه',
  'refusedAtDoor': 'رفضه عند الباب',
  'refusedConfirm': 'رفض المشتري الطرد؟ تعود منتجاته إلى رفّك.',
  'driverLabel': 'المندوب',
  'didYouReceive': 'هل استلمت طلبك؟',
  'yesReceived': 'نعم، استلمته',
  'noNotReceived': 'لا',
  'receiptProblemNote': 'أبلغنا المتجر، وسيتصل بك.',
  'returnCashNote': 'يأخذ المتجر المنتج ويعيد لك المبلغ نقداً.',
  'returnWindowNote': 'يمكنك الإرجاع خلال 7 أيام من الاستلام.',
  'notOnThisReturn': 'غير مشمول بهذا الإرجاع',
  'notDeliveredYetReturn': 'لم يُسلَّم بعد. يمكن إرجاعه بعد وصوله.',
  'cancelledNothingToReturn': 'أُلغي، فلا يوجد ما يُرجَع.',
  'returnedOrLate': 'أُرجِع من قبل، أو مضت أيامه السبعة.',
  'nothingToReturnNow': 'لا شيء في هذا الطلب يمكن إرجاعه الآن.',
  'returnRequests': 'طلبات الإرجاع',
  'approveReturn': 'موافقة واستلام المنتج',
  'declineReturn': 'رفض',
  'cashHandedBack': 'تم الاستلام وإعادة المبلغ نقداً',
  'oweSaba': 'المستحق لسبأ',
  'oweThisMonth': 'هذا الشهر حتى الآن',
  'deliveredSales': 'مبيعات تم توصيلها',
  'returnedCash': 'مبالغ أُعيدت في المرتجعات',
  'sabaShare': 'حصة سبأ',
  'youOwe': 'المبلغ المستحق',
  'oweHowItWorks':
      'تُحتسب الطلبات المُسلَّمة فقط، وتُخصم المرتجعات. أجرة التوصيل لك بالكامل. تدفع لسبأ في بداية الشهر التالي.',
  'pastMonths': 'الأشهر السابقة',
  'noPastMonths': 'لا توجد أشهر سابقة بعد.',
  'billDue': 'مستحق',
  'billPaid': 'مدفوع',
  'billPaidOnTemplate': 'دُفع في {date}',
  'billNothingOwed': 'لا شيء للدفع',
  'storeClosedNow': 'مغلق الآن',
  'storeClosedBuyNote': 'هذا المتجر مغلق الآن. عُد لاحقاً.',
  'storeNowOpen': 'متجرك مفتوح. يمكن للمتسوقين الطلب.',
  'storeNowClosed': 'متجرك مغلق. لا يمكن للمتسوقين الطلب حتى تفتحه.',
  'nameInArabic': 'الاسم بالعربية',
  'nameInEnglish': 'الاسم بالإنجليزية',
  'validationArabicLetters': 'اكتبه بحروف عربية',
  'termsOfUse': 'شروط الاستخدام',
  'privacyPolicy': 'سياسة الخصوصية',
  'legalUpdated': 'آخر تحديث 1 تشرين الأول 2026',
  'aboutSaba': 'عن سبأ',
  'agreeToTerms': 'إنشاء حساب يعني موافقتك على قواعد سبأ:',
  'returnRuleShort': 'إرجاع خلال 7 أيام واسترداد نقدي',
  'returnRuleStore':
      'الإرجاع: 7 أيام بعد التوصيل واسترداد نقدي. القاعدة واحدة في كل متاجر سبأ.',
  'allCities': 'كل المدن',
  'deliveryAvailable': 'التوصيل متاح',

  // The demo admin: the one screen that answers what is waiting.

  // Rating the store that delivered, once an order has arrived (§20).
  'howWasYourOrder': 'كيف كان طلبك؟',
  'returnDeclineUsed': 'تم استعماله',
  'returnDeclineIncomplete': 'ينقصه شيء من العلبة',
  'returnDeclineNotAsSaid': 'ليس كما قال المتسوق',
  'whyDecliningReturn': 'لماذا ترفض هذا الإرجاع؟',
  'confirmApproveReturn': 'تستلم المنتج وتعيد المبلغ نقداً عند استلامه.',
  'confirmCashBack': 'هل أعدت المبلغ نقداً؟ بهذا ينتهي الإرجاع.',
  'didYourOrderArrive': 'هل وصلك طلبك؟',
  'yesItArrived': 'نعم، وصل',
  'notYet': 'لم يصل بعد',
  'notNow': 'ليس الآن',
  'anythingToAdd': 'هل تريد إضافة شيء؟',
  'stockIsPerOption': 'يُضبط المخزون لكل خيار أدناه.',
  'merchantRejectedBanner':
      'لم توافق سبأ على متجرك، لذلك لا يمكنه البيع بعد. راسل الدعم '
      'لمعرفة ما يجب تغييره وأعد الطلب.',
  'storePreview': 'هكذا يرى المشترون متجرك',
  'previewNotListed': 'أنت وحدك ترى هذا المنتج، ولا يراه المشترون.',
  'backToDashboard': 'لوحة التحكم',
  'setUpYourStore': 'جهّز متجرك',
  'stepAddFirstProduct': 'أضف أول منتج',
  'stepSetDelivery': 'حدّد سعر التوصيل وأين توصّل',
  'stepWaitForApproval': 'انتظر موافقة سبأ',
  'storeWaitingApproval': 'بانتظار الموافقة',
  'storeApprovedOpen': 'مفتوح للطلبات',
  'storeApprovedClosed': 'مغلق بقرارك',
  'storeNotApproved': 'غير مُوافق عليه',
  'sendForApproval': 'إرسال للموافقة',
  'sendForApprovalHint': 'تتحقق منه سبأ، ثم يُعرض للبيع.',
  'productSaved': 'تم الحفظ.',
  'priceStepHint': 'بمضاعفات 250 د.ع، مثل 12,250 أو 12,500.',
  'waitingForApproval': 'بانتظار الموافقة',
  'storeLogo': 'صورة المتجر أو شعاره',
  'previewWaitingMessage': 'تظهر منتجاتك هنا بعد أن توافق عليها سبأ.',
  'listSeparator': '، ',
  'nounItem': 'منتج واحد|منتجان|منتجين|منتجات|منتجًا|منتج',
  'nounCharacter': 'حرفاً واحداً|حرفان|حرفين|أحرف|حرفاً|حرف',
  'nounProduct': 'منتج واحد|منتجان|منتجين|منتجات|منتجًا|منتج',
  'nounStore': 'متجر واحد|متجران|متجرين|متاجر|متجرًا|متجر',
  'nounOrder': 'طلب واحد|طلبان|طلبين|طلبات|طلبًا|طلب',
  'nounResult': 'نتيجة واحدة|نتيجتان|نتيجتين|نتائج|نتيجةً|نتيجة',
  'nounCustomer': 'زبون واحد|زبونان|زبونين|زبائن|زبونًا|زبون',
  'nounReturnRequest':
      'طلب إرجاع واحد|طلبا إرجاع|طلبي إرجاع|طلبات إرجاع|طلب إرجاع|طلب إرجاع',
  'nounDay': 'يوم واحد|يومان|يومين|أيام|يومًا|يوم',
  'nounHour': 'ساعة واحدة|ساعتان|ساعتين|ساعات|ساعةً|ساعة',
  'nounMinute': 'دقيقة واحدة|دقيقتان|دقيقتين|دقائق|دقيقةً|دقيقة',
  'nounSecond': 'ثانية واحدة|ثانيتان|ثانيتين|ثوانٍ|ثانيةً|ثانية',
  'nounTime': 'مرة واحدة|مرتان|مرتين|مرات|مرةً|مرة',
  'resendInTemplate': 'إعادة الإرسال بعد {time}',
  'waitingForTemplate': 'ينتظر منذ {time}',
  'toConfirmSuffix': 'بانتظار التأكيد',
  'waitingReplySuffix': 'بانتظار ردك',
  'outOfStockSuffix': 'بلا مخزون',
  'notApprovedSuffix': 'دون موافقة',
  'freeDelivery': 'توصيل مجاني',
  'takenDown': 'موقوف',
  'takenDownBySaba': 'أوقف سبأ عرضه',
  'sabaSaidNo': 'لم يوافق سبأ على هذا المنتج',
  'fixAndResend': 'عدّل ما يطلبه السبب وأرسله مرة أخرى.',
  'editApprovedNote':
      'تغيير الاسم أو الوصف أو الضمان أو الفئة أو الصور أو الخيارات يعيده '
      'إلى سبأ للمراجعة، فيخرج من المتجر حتى تتم الموافقة عليه. تغيير السعر '
      'والمخزون لا يعيده.',
  'noteOrderReceived': 'وصل الطلب',
  'reasonCustomerCancelled': 'ألغاه الزبون',
  'notInTotalTemplate': 'غير محسوب في المجموع: {reason}',
  'productNotFound': 'هذا المنتج غير متوفر',
  'productNotFoundMessage': 'ربما سُحب من البيع، أو أن الرابط غير صحيح.',
  'cancelledNothingCharged': 'أُلغي الطلب: لن يُدفع أي مبلغ منه.',
  'refusedNothingPaid': 'رُفض عند الباب: لم يُدفع أي مبلغ.',
};
